#DELETE FROM `configuration` WHERE `configuration_key` LIKE 'VARIO%';
DELETE FROM `address_book` WHERE `customers_id` > 1;
DELETE FROM `admin_access` WHERE `customers_id` > '1';
DELETE FROM `customers` WHERE `customers_id` > 1;
DELETE FROM `customers_info` WHERE `customers_info_id` > 1;
DELETE FROM `customers_ip` WHERE `customers_id` > 1;
DELETE FROM `customers_memo` WHERE `customers_id` > 1;
DELETE FROM `customers_status_history` WHERE `customers_id` > 1;
TRUNCATE `categories`;
TRUNCATE `categories_description`;
#UPDATE `products` SET `products_status`=0;
TRUNCATE `products`;
TRUNCATE `products_images`;
TRUNCATE `products_content`;
TRUNCATE `products_description`;
TRUNCATE `products_to_categories`;
TRUNCATE `products_attributes`;
TRUNCATE `products_attributes_download`;
TRUNCATE `products_options`;
TRUNCATE `products_options_values`;
TRUNCATE `products_options_values_to_products_options`;
truncate `products_properties_combis`;
truncate `products_properties_index`;
truncate `products_properties_combis_values`;
truncate `properties`;
truncate `properties_description`;
truncate `properties_values`;
truncate `properties_values_description`;
TRUNCATE `specials`;
TRUNCATE `personal_offers_by_customers_status_0`;
TRUNCATE `personal_offers_by_customers_status_1`;
TRUNCATE `personal_offers_by_customers_status_2`;
TRUNCATE `personal_offers_by_customers_status_3`;
TRUNCATE `manufacturers`;
TRUNCATE `manufacturers_info`;
## Die folgenden Zeilen nur bei Tests mit leerem Shop aktivieren
TRUNCATE `orders`;
TRUNCATE `orders`;
TRUNCATE `orders_products`;
TRUNCATE `orders_products_attributes`;
TRUNCATE `orders_status_history`;
TRUNCATE `orders_total`;
TRUNCATE `vario_adr`;
TRUNCATE `vario_art`;
TRUNCATE `vario_gfx`;
