INSERT INTO admin_navigation VALUES (NULL, 'categories', 'Categories / Produtcs', 'products', 'categories.php', NULL, 1, NULL, 1);
INSERT INTO admin_navigation VALUES (NULL, 'categories', 'Kategorien / Artikel', 'products', 'categories.php', NULL, 2, NULL, 1);
INSERT INTO admin_navigation VALUES (NULL, 'new_attributes', 'New Attributes', 'products', 'new_attributes.php', NULL, 1, NULL, 2);
INSERT INTO admin_navigation VALUES (NULL, 'new_attributes', 'Attribut Verwaltung', 'products', 'new_attributes.php', NULL, 2, NULL, 2);
INSERT INTO admin_navigation VALUES (NULL, 'products_attributes', 'Attributes', 'products', 'products_attributes.php', NULL, 1, NULL, 3);
INSERT INTO admin_navigation VALUES (NULL, 'products_attributes', 'Artikelmerkmale', 'products', 'products_attributes.php', NULL, 2, NULL, 3);
INSERT INTO admin_navigation VALUES (NULL, 'manufacturers', 'Manufacturers', 'products', 'manufacturers.php', NULL, 1, NULL, 4);
INSERT INTO admin_navigation VALUES (NULL, 'manufacturers', 'Hersteller', 'products', 'manufacturers.php', NULL, 2, NULL, 4);
INSERT INTO admin_navigation VALUES (NULL, 'reviews', 'Reviews', 'products', 'reviews.php', NULL, 1, NULL, 12);
INSERT INTO admin_navigation VALUES (NULL, 'reviews', 'Artikelbewertungen', 'products', 'reviews.php', NULL, 2, NULL, 12);
INSERT INTO admin_navigation VALUES (NULL, 'specials', 'Specials', 'products', 'specials.php', NULL, 1, NULL, 5);
INSERT INTO admin_navigation VALUES (NULL, 'specials', 'Sonderangebote', 'products', 'specials.php', NULL, 2, NULL, 5);
INSERT INTO admin_navigation VALUES (NULL, 'products_expected', 'Products expected', 'products', 'products_expected.php', NULL, 1, NULL, 6);
INSERT INTO admin_navigation VALUES (NULL, 'products_expected', 'Erwartete Artikel', 'products', 'products_expected.php', NULL, 2, NULL, 6);
INSERT INTO admin_navigation VALUES (NULL, 'accessories', 'Accessories', 'products', 'accessories.php', NULL, 1, NULL, 7);
INSERT INTO admin_navigation VALUES (NULL, 'accessories', 'Zubehör', 'products', 'accessories.php', NULL, 2, NULL, 7);
INSERT INTO admin_navigation VALUES (NULL, 'price_change', 'Lagerbestände', 'products', 'price_change.php', NULL, 1, NULL, 8);
INSERT INTO admin_navigation VALUES (NULL, 'price_change', 'Lagerbestände', 'products', 'price_change.php', NULL, 2, NULL, 8);
INSERT INTO admin_navigation VALUES (NULL, 'global_products_price', 'Price Update', 'products', 'global_products_price.php', NULL, 1, NULL, 9);
INSERT INTO admin_navigation VALUES (NULL, 'global_products_price', 'Preis Aktualisierung', 'products', 'global_products_price.php', NULL, 2, NULL, 9);
INSERT INTO admin_navigation VALUES (NULL, 'product_filter', 'Product Filter', 'products', 'product_filter.php', NULL, 1, NULL, 10);
INSERT INTO admin_navigation VALUES (NULL, 'product_filter', 'Produkt Filter', 'products', 'product_filter.php', NULL, 2, NULL, 10);
INSERT INTO admin_navigation VALUES (NULL, 'configuration', 'Productview', 'products', 'configuration.php', 1002, 1, NULL, 11);
INSERT INTO admin_navigation VALUES (NULL, 'configuration', 'Produktdarstellung', 'products', 'configuration.php', 1002, 2, NULL, 11);

INSERT INTO admin_navigation VALUES (NULL, 'gv_sent', 'Coupon send', 'gift', 'gv_sent.php', NULL, 1, NULL, 1);
INSERT INTO admin_navigation VALUES (NULL, 'gv_sent', 'Kupon versendet', 'gift', 'gv_sent.php', NULL, 2, NULL, 1);
INSERT INTO admin_navigation VALUES (NULL, 'gv_mail', 'Coupon Mail', 'gift', 'gv_mail.php', NULL, 1, NULL, 1);
INSERT INTO admin_navigation VALUES (NULL, 'gv_mail', 'Kupon Mail', 'gift', 'gv_mail.php', NULL, 2, NULL, 1);
INSERT INTO admin_navigation VALUES (NULL, 'coupon_admin', 'Coupon Admin', 'gift', 'coupon_admin.php', NULL, 1, NULL, 1);
INSERT INTO admin_navigation VALUES (NULL, 'coupon_admin', 'Kupon Admin', 'gift', 'coupon_admin.php', NULL, 2, NULL, 1);

INSERT INTO admin_navigation VALUES (NULL, 'customers', 'Customers', 'customers', 'customers.php', NULL, 1, NULL, 1);
INSERT INTO admin_navigation VALUES (NULL, 'customers', 'Kunden', 'customers', 'customers.php', NULL, 2, NULL, 1);
INSERT INTO admin_navigation VALUES (NULL, 'customers_status', 'Customers Status', 'customers', 'customers_status.php', NULL, 1, NULL, 2);
INSERT INTO admin_navigation VALUES (NULL, 'customers_status', 'Kundengruppe', 'customers', 'customers_status.php', NULL, 2, NULL, 2);
INSERT INTO admin_navigation VALUES (NULL, 'orders', 'Orders', 'customers', 'orders.php', NULL, 1, NULL, 3);
INSERT INTO admin_navigation VALUES (NULL, 'orders', 'Bestellungen', 'customers', 'orders.php', NULL, 2, NULL, 3);
INSERT INTO admin_navigation VALUES (NULL, 'paypal', 'PayPal', 'customers', 'paypal.php', NULL, 1, NULL, 4);
INSERT INTO admin_navigation VALUES (NULL, 'paypal', 'PayPal Zahlungen', 'customers', 'paypal.php', NULL, 2, NULL, 4);
INSERT INTO admin_navigation VALUES (NULL, 'customers_sik', 'Customer Sik', 'customers', 'customers_sik.php', NULL, 1, NULL, 5);
INSERT INTO admin_navigation VALUES (NULL, 'customers_sik', 'gelöschte Kunden', 'customers', 'customers_sik.php', NULL, 2, NULL, 5);
INSERT INTO admin_navigation VALUES (NULL, 'recover_cart_sales', 'Recover cart sales', 'customers', 'recover_cart_sales.php', NULL, 1, NULL, 6);
INSERT INTO admin_navigation VALUES (NULL, 'recover_cart_sales', 'Offene Warenkörbe', 'customers', 'recover_cart_sales.php', NULL, 2, NULL, 6);
INSERT INTO admin_navigation VALUES (NULL, 'recover_wish_list', 'Recover Wish Lists', 'customers', 'recover_wish_list.php', NULL, 1, NULL, 7);
INSERT INTO admin_navigation VALUES (NULL, 'recover_wish_list', 'Offene Merkzettel', 'customers', 'recover_wish_list.php', NULL, 2, NULL, 7);
INSERT INTO admin_navigation VALUES (NULL, 'customers_aquise', 'Customers Aquise', 'customers', 'customers_aquise.php', NULL, 1, NULL, 8);
INSERT INTO admin_navigation VALUES (NULL, 'customers_aquise', 'Kunden CRM', 'customers', 'customers_aquise.php', NULL, 2, NULL, 8);
INSERT INTO admin_navigation VALUES (NULL, 'orders_overview', 'Orders Overview', 'customers', 'orders_overview.php', NULL, 1, NULL, 9);
INSERT INTO admin_navigation VALUES (NULL, 'orders_overview', 'Bestellübersicht', 'customers', 'orders_overview.php', NULL, 2, NULL, 9);

INSERT INTO admin_navigation VALUES (NULL, 'modules', 'Payment', 'modules', 'modules.php', NULL, 1, 'payment', 1);
INSERT INTO admin_navigation VALUES (NULL, 'modules', 'Zahlarten', 'modules', 'modules.php', NULL, 2, 'payment', 1);
INSERT INTO admin_navigation VALUES (NULL, 'modules', 'Shipping', 'modules', 'modules.php', NULL, 1, 'shipping', 2);
INSERT INTO admin_navigation VALUES (NULL, 'modules', 'Versandarten', 'modules', 'modules.php', NULL, 2, 'shipping', 2);
INSERT INTO admin_navigation VALUES (NULL, 'modules', 'Order Total', 'modules', 'modules.php', NULL, 1, 'ordertotal', 3);
INSERT INTO admin_navigation VALUES (NULL, 'modules', 'Zusammenfassung', 'modules', 'modules.php', NULL, 2, 'ordertotal', 3);
INSERT INTO admin_navigation VALUES (NULL, 'module_system', 'System Modules', 'modules', 'module_system.php', NULL, 1, NULL, 4);
INSERT INTO admin_navigation VALUES (NULL, 'module_system', 'System Module', 'modules', 'module_system.php', NULL, 2, NULL, 4);
INSERT INTO admin_navigation VALUES (NULL, 'module_install', 'Install / Update', 'modules', 'module_install.php', NULL, 1, NULL, 5);
INSERT INTO admin_navigation VALUES (NULL, 'module_install', 'Installation / Update', 'modules', 'module_install.php', NULL, 2, NULL, 5);
INSERT INTO admin_navigation VALUES (NULL, 'module_export', 'Export Modules', 'modules', 'module_export.php', NULL, 1, NULL, 5);
INSERT INTO admin_navigation VALUES (NULL, 'module_export', 'Export Module', 'modules', 'module_export.php', NULL, 2, NULL, 5);
INSERT INTO admin_navigation VALUES (NULL, 'cseo_product_export', 'Export Produkte', 'modules', 'cseo_product_export.php', NULL, 2, NULL, 5);
INSERT INTO admin_navigation VALUES (NULL, 'cseo_product_export', 'Export Products', 'modules', 'cseo_product_export.php', NULL, 1, NULL, 5);
INSERT INTO admin_navigation VALUES (NULL, 'novalnet', 'Novalnet', 'modules', 'novalnet.php', NULL, 1, NULL, 6);
INSERT INTO admin_navigation VALUES (NULL, 'novalnet', 'Novalnet', 'modules', 'novalnet.php', NULL, 2, NULL, 6);
INSERT INTO admin_navigation VALUES (NULL, 'magnalister', 'magnalister', 'modules', 'magnalister.php', NULL, 1, NULL, 7);
INSERT INTO admin_navigation VALUES (NULL, 'magnalister', 'magnalister', 'modules', 'magnalister.php', NULL, 2, NULL, 7);
INSERT INTO admin_navigation VALUES (NULL, 'haendlerbund', 'Haendlerbund', 'modules', 'haendlerbund.php', NULL, 1, NULL, 8);
INSERT INTO admin_navigation VALUES (NULL, 'haendlerbund', 'Haendlerbund', 'modules', 'haendlerbund.php', NULL, 2, NULL, 8);

INSERT INTO admin_navigation VALUES (NULL, 'whos_online', 'Whos Online', 'statistics', 'whos_online.php', NULL, 1, NULL, 1);
INSERT INTO admin_navigation VALUES (NULL, 'whos_online', 'Wer ist Online', 'statistics', 'whos_online.php', NULL, 2, NULL, 1);
INSERT INTO admin_navigation VALUES (NULL, 'stats_products_viewed', 'Products viewed', 'statistics', 'stats_products_viewed.php', NULL, 1, NULL, 2);
INSERT INTO admin_navigation VALUES (NULL, 'stats_products_viewed', 'Besuchte Produkte', 'statistics', 'stats_products_viewed.php', NULL, 2, NULL, 2);
INSERT INTO admin_navigation VALUES (NULL, 'stats_products_purchased', 'Products purchased', 'statistics', 'stats_products_purchased.php', NULL, 1, NULL, 3);
INSERT INTO admin_navigation VALUES (NULL, 'stats_products_purchased', 'Umsatzstärkste Produkte', 'statistics', 'stats_products_purchased.php', NULL, 2, NULL, 3);
INSERT INTO admin_navigation VALUES (NULL, 'stats_customers', 'Customers Statistic', 'statistics', 'stats_customers.php', NULL, 1, NULL, 4);
INSERT INTO admin_navigation VALUES (NULL, 'stats_customers', 'Bestellstatistik', 'statistics', 'stats_customers.php', NULL, 2, NULL, 4);
INSERT INTO admin_navigation VALUES (NULL, 'stats_sales_report', 'Sales Report', 'statistics', 'stats_sales_report.php', NULL, 1, NULL, 5);
INSERT INTO admin_navigation VALUES (NULL, 'stats_sales_report', 'Umsatzstatistik', 'statistics', 'stats_sales_report.php', NULL, 2, NULL, 5);
INSERT INTO admin_navigation VALUES (NULL, 'stats_stock_warning', 'Stock Warning', 'statistics', 'stats_stock_warning.php', NULL, 1, NULL, 6);
INSERT INTO admin_navigation VALUES (NULL, 'stats_stock_warning', 'Lagerbestände', 'statistics', 'stats_stock_warning.php', NULL, 2, NULL, 6);
INSERT INTO admin_navigation VALUES (NULL, 'stats_campaigns', 'Campaigns Report', 'statistics', 'stats_campaigns.php', NULL, 1, NULL, 7);
INSERT INTO admin_navigation VALUES (NULL, 'stats_campaigns', 'Kampagnen Report', 'statistics', 'stats_campaigns.php', NULL, 2, NULL, 7);
INSERT INTO admin_navigation VALUES (NULL, 'stats_keywords_all', 'Keywords Statistic', 'statistics', 'stats_keywords_all.php', NULL, 1, NULL, 8);
INSERT INTO admin_navigation VALUES (NULL, 'stats_keywords_all', 'Suchbegriff Statistik', 'statistics', 'stats_keywords_all.php', NULL, 2, NULL, 8);
INSERT INTO admin_navigation VALUES (NULL, 'stats_recover_cart_sales', 'Open Carts', 'statistics', 'stats_recover_cart_sales.php', NULL, 1, NULL, 9);
INSERT INTO admin_navigation VALUES (NULL, 'stats_recover_cart_sales', 'Offene Warenkörbe', 'statistics', 'stats_recover_cart_sales.php', NULL, 2, NULL, 9);

INSERT INTO admin_navigation VALUES (NULL, 'module_newsletter_products', 'Newsletter Products', 'tools', 'module_newsletter_products.php', NULL, 1, NULL, 1);
INSERT INTO admin_navigation VALUES (NULL, 'module_newsletter_products', 'Newsletter Produkte', 'tools', 'module_newsletter_products.php', NULL, 2, NULL, 1);
INSERT INTO admin_navigation VALUES (NULL, 'module_newsletter', 'Newsletter', 'tools', 'module_newsletter.php', NULL, 1, NULL, 2);
INSERT INTO admin_navigation VALUES (NULL, 'module_newsletter', 'Newsletter', 'tools', 'module_newsletter.php', NULL, 2, NULL, 2);
INSERT INTO admin_navigation VALUES (NULL, 'content_manager', 'Content Manager', 'tools', 'content_manager.php', NULL, 1, NULL, 3);
INSERT INTO admin_navigation VALUES (NULL, 'content_manager', 'Content Manager', 'tools', 'content_manager.php', NULL, 2, NULL, 3);
INSERT INTO admin_navigation VALUES (NULL, 'blog', 'Blog Manager', 'tools', 'blog.php', NULL, 1, NULL, 4);
INSERT INTO admin_navigation VALUES (NULL, 'blog', 'Blog Manager', 'tools', 'blog.php', NULL, 2, NULL, 4);
INSERT INTO admin_navigation VALUES (NULL, 'backup', 'Backup Manager', 'tools', 'backup.php', NULL, 1, NULL, 6);
INSERT INTO admin_navigation VALUES (NULL, 'backup', 'Backup Manager', 'tools', 'backup.php', NULL, 2, NULL, 6);
INSERT INTO admin_navigation VALUES (NULL, 'banner_manager', 'Banner Manager', 'tools', 'banner_manager.php', NULL, 1, NULL, 7);
INSERT INTO admin_navigation VALUES (NULL, 'banner_manager', 'Banner Manager', 'tools', 'banner_manager.php', NULL, 2, NULL, 7);
INSERT INTO admin_navigation VALUES (NULL, 'css_styler', 'CSS Buttons', 'tools', 'css_styler.php', NULL, 1, NULL, 1);
INSERT INTO admin_navigation VALUES (NULL, 'css_styler', 'CSS Buttons', 'tools', 'css_styler.php', NULL, 2, NULL, 1);
INSERT INTO admin_navigation VALUES (NULL, 'box_manager', 'Box Manager', 'tools', 'box_manager.php', NULL, 1, NULL, 1);
INSERT INTO admin_navigation VALUES (NULL, 'box_manager', 'Boxen Manager', 'tools', 'box_manager.php', NULL, 2, NULL, 1);
INSERT INTO admin_navigation VALUES (NULL, 'news_ticker', 'News Ticker', 'tools', 'news_ticker.php', NULL, 1, NULL, 1);
INSERT INTO admin_navigation VALUES (NULL, 'news_ticker', 'News Ticker', 'tools', 'news_ticker.php', NULL, 2, NULL, 1);
INSERT INTO admin_navigation VALUES (NULL, 'server_info', 'Server Info', 'tools', 'server_info.php', NULL, 1, NULL, 8);
INSERT INTO admin_navigation VALUES (NULL, 'server_info', 'Server Info', 'tools', 'server_info.php', NULL, 2, NULL, 8);
INSERT INTO admin_navigation VALUES (NULL, 'csv_backend', 'CSV Import/Export', 'tools', 'csv_backend.php', NULL, 1, NULL, 9);
INSERT INTO admin_navigation VALUES (NULL, 'csv_backend', 'CSV Import/Export', 'tools', 'csv_backend.php', NULL, 2, NULL, 9);
INSERT INTO admin_navigation VALUES (NULL, 'database_manager', 'SQL Tool', 'tools', 'database_manager.php', NULL, 1, NULL, 10);
INSERT INTO admin_navigation VALUES (NULL, 'database_manager', 'SQL Tool', 'tools', 'database_manager.php', NULL, 2, NULL, 10);
INSERT INTO admin_navigation VALUES (NULL, 'google_sitemap', 'Google Sitemap', 'tools', '../google_sitemap.php?auto=true&ping=true', NULL, 1, NULL, 11);
INSERT INTO admin_navigation VALUES (NULL, 'google_sitemap', 'Google Sitemap', 'tools', '../google_sitemap.php?auto=true&ping=true', NULL, 2, NULL, 11);
INSERT INTO admin_navigation VALUES (NULL, 'delete_cache', 'delete Cache', 'tools', 'delete_cache.php', NULL, 1, NULL, 12);
INSERT INTO admin_navigation VALUES (NULL, 'delete_cache', 'Cache leeren', 'tools', 'delete_cache.php', NULL, 2, NULL, 12);
INSERT INTO admin_navigation VALUES (NULL, 'removeoldpics', 'remove old Pics', 'tools', 'removeoldpics.php', NULL, 1, NULL, 13);
INSERT INTO admin_navigation VALUES (NULL, 'removeoldpics', 'alte Bilder löschen', 'tools', 'removeoldpics.php', NULL, 2, NULL, 13);
INSERT INTO admin_navigation VALUES (NULL, 'cseo_imageprocessing', 'Pics rendering', 'tools', 'cseo_imageprocessing.php', NULL, 1, NULL, 14);
INSERT INTO admin_navigation VALUES (NULL, 'cseo_imageprocessing', 'Bilder neu erstellen', 'tools', 'cseo_imageprocessing.php', NULL, 2, NULL, 14);

INSERT INTO admin_navigation VALUES (NULL, 'configuration', 'Base-Configuration', 'seo_config', 'configuration.php', 155, 1, NULL, 1);
INSERT INTO admin_navigation VALUES (NULL, 'configuration', 'Grundkonfiguration', 'seo_config', 'configuration.php', 155, 2, NULL, 1);

INSERT INTO admin_navigation VALUES (NULL, 'product_listings', 'Product Listings', 'seo_config', 'product_listings.php', NULL, 1, NULL, 1);
INSERT INTO admin_navigation VALUES (NULL, 'product_listings', 'Produktlisten-Einstellung', 'seo_config', 'product_listings.php', NULL, 2, NULL, 1);
INSERT INTO admin_navigation VALUES (NULL, 'orders_pdf_profiler', 'PDF WAWI Config', 'seo_config', 'orders_pdf_profiler.php', NULL, 1, NULL, 1);
INSERT INTO admin_navigation VALUES (NULL, 'orders_pdf_profiler', 'PDF WAWI Einstellung', 'seo_config', 'orders_pdf_profiler.php', NULL, 2, NULL, 1);
INSERT INTO admin_navigation VALUES (NULL, 'personal_links', 'Personal Links', 'seo_config', 'personal_links.php', NULL, 1, NULL, 1);
INSERT INTO admin_navigation VALUES (NULL, 'personal_links', 'Personal Links', 'seo_config', 'personal_links.php', NULL, 2, NULL, 1);
INSERT INTO admin_navigation VALUES (NULL, 'configuration', 'Frontpage - Config', 'seo_config', 'configuration.php', 1000, 1, NULL, 1);
INSERT INTO admin_navigation VALUES (NULL, 'configuration', 'Startseite - Einstellung', 'seo_config', 'configuration.php', 1000, 2, NULL, 1);
INSERT INTO admin_navigation VALUES (NULL, 'configuration', 'Twitter Box', 'seo_config', 'configuration.php', 1001, 1, NULL, 1);
INSERT INTO admin_navigation VALUES (NULL, 'configuration', 'Twitter Box', 'seo_config', 'configuration.php', 1001, 2, NULL, 1);
INSERT INTO admin_navigation VALUES (NULL, 'configuration', 'Recover Carts', 'seo_config', 'configuration.php', 33, 1, NULL, 1);
INSERT INTO admin_navigation VALUES (NULL, 'configuration', 'Offene Warenkörbe', 'seo_config', 'configuration.php', 33, 2, NULL, 1);
INSERT INTO admin_navigation VALUES (NULL, 'configuration', 'Security Settings', 'seo_config', 'configuration.php', 363, 1, NULL, 1);
INSERT INTO admin_navigation VALUES (NULL, 'configuration', 'Sicherheitseinstellungen', 'seo_config', 'configuration.php', 363, 2, NULL, 1);
INSERT INTO admin_navigation VALUES (NULL, 'configuration', 'Order Process', 'seo_config', 'configuration.php', 333, 1, NULL, 1);
INSERT INTO admin_navigation VALUES (NULL, 'configuration', 'Bestellprozess', 'seo_config', 'configuration.php', 333, 2, NULL, 1);
INSERT INTO admin_navigation VALUES (NULL, 'configuration', 'PayPal Express', 'seo_config', 'configuration.php', 25, 1, NULL, 1);
INSERT INTO admin_navigation VALUES (NULL, 'configuration', 'PayPal Express', 'seo_config', 'configuration.php', 25, 2, NULL, 1);
INSERT INTO admin_navigation VALUES (NULL, 'cseo_language_button', 'button languages', 'seo_config', 'cseo_language_button.php', NULL, 1, NULL, 1);
INSERT INTO admin_navigation VALUES (NULL, 'cseo_language_button', 'Button Sprache', 'seo_config', 'cseo_language_button.php', NULL, 2, NULL, 1);
INSERT INTO admin_navigation VALUES (NULL, 'cseo_ids', 'number Ranges', 'seo_config', 'cseo_ids.php', NULL, 1, NULL, 1);
INSERT INTO admin_navigation VALUES (NULL, 'cseo_ids', 'Nummernkreise', 'seo_config', 'cseo_ids.php', NULL, 2, NULL, 1);
INSERT INTO admin_navigation VALUES (NULL, 'cseo_antispam', 'Anti-SPAM', 'seo_config', 'cseo_antispam.php', NULL, 1, NULL, 1);
INSERT INTO admin_navigation VALUES (NULL, 'cseo_antispam', 'Anti-SPAM', 'seo_config', 'cseo_antispam.php', NULL, 2, NULL, 1);
INSERT INTO admin_navigation VALUES (NULL, 'configuration', 'Admin Config', 'seo_config', 'configuration.php', 1003, 1, NULL, 1);
INSERT INTO admin_navigation VALUES (NULL, 'configuration', 'Admin Einstellungen', 'seo_config', 'configuration.php', 1003, 2, NULL, 1);
INSERT INTO admin_navigation VALUES (NULL, 'configuration', 'Treepodia', 'seo_config', 'configuration.php', 1004, 1, NULL, 1);
INSERT INTO admin_navigation VALUES (NULL, 'configuration', 'Treepodia', 'seo_config', 'configuration.php', 1004, 2, NULL, 1);
INSERT INTO admin_navigation VALUES (NULL, 'cseo_redirect', 'Redirect Setting', 'seo_config', 'cseo_redirect.php', NULL, 1, NULL, 1);
INSERT INTO admin_navigation VALUES (NULL, 'cseo_redirect', 'Umleitungen definieren', 'seo_config', 'cseo_redirect.php', NULL, 2, NULL, 1);
INSERT INTO admin_navigation VALUES (NULL, 'configuration', 'Trusted Shops', 'seo_config', 'configuration.php', 156, 1, NULL, 1);
INSERT INTO admin_navigation VALUES (NULL, 'configuration', 'Trusted Shops', 'seo_config', 'configuration.php', 156, 2, NULL, 1);
INSERT INTO admin_navigation VALUES (NULL, 'janolaw', 'Janolaw', 'seo_config', 'janolaw.php', NULL, 1, NULL, 1);
INSERT INTO admin_navigation VALUES (NULL, 'janolaw', 'Janolaw', 'seo_config', 'janolaw.php', NULL, 2, NULL, 1);
INSERT INTO admin_navigation VALUES (NULL, 'configuration', 'Tracking & Analytics', 'seo_config', 'configuration.php', 361, 1, NULL, 1);
INSERT INTO admin_navigation VALUES (NULL, 'configuration', 'Tracking & Analytics', 'seo_config', 'configuration.php', 361, 2, NULL, 1);
INSERT INTO admin_navigation VALUES (NULL, 'configuration', 'Retouren Einstellungen', 'seo_config', 'configuration.php', 1005, 1, NULL, 30);
INSERT INTO admin_navigation VALUES (NULL, 'configuration', 'RMA Settings', 'seo_config', 'configuration.php', 1005, 2, NULL, 30);

INSERT INTO admin_navigation VALUES (NULL, 'languages', 'Languages', 'zones', 'languages.php', NULL, 1, NULL, 1);
INSERT INTO admin_navigation VALUES (NULL, 'languages', 'Sprachen', 'zones', 'languages.php', NULL, 2, NULL, 1);
INSERT INTO admin_navigation VALUES (NULL, 'countries', 'Countries', 'zones', 'countries.php', NULL, 1, NULL, 1);
INSERT INTO admin_navigation VALUES (NULL, 'countries', 'Länder', 'zones', 'countries.php', NULL, 2, NULL, 1);
INSERT INTO admin_navigation VALUES (NULL, 'currencies', 'Currencies', 'zones', 'currencies.php', NULL, 1, NULL, 1);
INSERT INTO admin_navigation VALUES (NULL, 'currencies', 'Währungen', 'zones', 'currencies.php', NULL, 2, NULL, 1);
INSERT INTO admin_navigation VALUES (NULL, 'zones', 'Zones', 'zones', 'zones.php', NULL, 1, NULL, 1);
INSERT INTO admin_navigation VALUES (NULL, 'zones', 'Bundesländer', 'zones', 'zones.php', NULL, 2, NULL, 1);
INSERT INTO admin_navigation VALUES (NULL, 'geo_zones', 'Tax Zones', 'zones', 'geo_zones.php', NULL, 1, NULL, 1);
INSERT INTO admin_navigation VALUES (NULL, 'geo_zones', 'Steuerzonen', 'zones', 'geo_zones.php', NULL, 2, NULL, 1);
INSERT INTO admin_navigation VALUES (NULL, 'tax_classes', 'Tax Classes', 'zones', 'tax_classes.php', NULL, 1, NULL, 1);
INSERT INTO admin_navigation VALUES (NULL, 'tax_classes', 'Steuerklassen', 'zones', 'tax_classes.php', NULL, 2, NULL, 1);
INSERT INTO admin_navigation VALUES (NULL, 'tax_rates', 'Tax Rates', 'zones', 'tax_rates.php', NULL, 1, NULL, 1);
INSERT INTO admin_navigation VALUES (NULL, 'tax_rates', 'Steuersätze', 'zones', 'tax_rates.php', NULL, 2, NULL, 1);

INSERT INTO admin_navigation VALUES (NULL, 'configuration', 'My Shop', 'config', 'configuration.php', 1, 1, NULL, 1);
INSERT INTO admin_navigation VALUES (NULL, 'configuration', 'Mein Shop', 'config', 'configuration.php', 1, 2, NULL, 1);
INSERT INTO admin_navigation VALUES (NULL, 'configuration', 'Minimum Values', 'config', 'configuration.php', 2, 1, NULL, 1);
INSERT INTO admin_navigation VALUES (NULL, 'configuration', 'Minimum Werte', 'config', 'configuration.php', 2, 2, NULL, 1);
INSERT INTO admin_navigation VALUES (NULL, 'configuration', 'Maximum Values', 'config', 'configuration.php', 3, 1, NULL, 1);
INSERT INTO admin_navigation VALUES (NULL, 'configuration', 'Maximum Werte', 'config', 'configuration.php', 3, 2, NULL, 1);
INSERT INTO admin_navigation VALUES (NULL, 'configuration', 'Image Options', 'config', 'configuration.php', 4, 1, NULL, 1);
INSERT INTO admin_navigation VALUES (NULL, 'configuration', 'Bild Optionen', 'config', 'configuration.php', 4, 2, NULL, 1);
INSERT INTO admin_navigation VALUES (NULL, 'configuration', 'Customer Details', 'config', 'configuration.php', 5, 1, NULL, 1);
INSERT INTO admin_navigation VALUES (NULL, 'configuration', 'Kunden Details', 'config', 'configuration.php', 5, 2, NULL, 1);
INSERT INTO admin_navigation VALUES (NULL, 'configuration', 'Shipping Options', 'config', 'configuration.php', 7, 1, NULL, 1);
INSERT INTO admin_navigation VALUES (NULL, 'configuration', 'Versand Optionen', 'config', 'configuration.php', 7, 2, NULL, 1);
INSERT INTO admin_navigation VALUES (NULL, 'configuration', 'Product Listing Options', 'config', 'configuration.php', 8, 1, NULL, 1);
INSERT INTO admin_navigation VALUES (NULL, 'configuration', 'Artikel Listen Optionen', 'config', 'configuration.php', 8, 2, NULL, 1);
INSERT INTO admin_navigation VALUES (NULL, 'configuration', 'Stock Options', 'config', 'configuration.php', 9, 1, NULL, 1);
INSERT INTO admin_navigation VALUES (NULL, 'configuration', 'Lagerverwaltungs Optionen', 'config', 'configuration.php', 9, 2, NULL, 1);
INSERT INTO admin_navigation VALUES (NULL, 'configuration', 'Logging Options', 'config', 'configuration.php', 10, 1, NULL, 1);
INSERT INTO admin_navigation VALUES (NULL, 'configuration', 'Logging Optionen', 'config', 'configuration.php', 10, 2, NULL, 1);
INSERT INTO admin_navigation VALUES (NULL, 'configuration', 'Cache Options', 'config', 'configuration.php', 11, 1, NULL, 1);
INSERT INTO admin_navigation VALUES (NULL, 'configuration', 'Cache Optionen', 'config', 'configuration.php', 11, 2, NULL, 1);
INSERT INTO admin_navigation VALUES (NULL, 'configuration', 'E-Mail Options', 'config', 'configuration.php', 12, 1, NULL, 1);
INSERT INTO admin_navigation VALUES (NULL, 'configuration', 'E-Mail Optionen', 'config', 'configuration.php', 12, 2, NULL, 1);
INSERT INTO admin_navigation VALUES (NULL, 'emails', 'E-Mail Templates', 'config', 'emails.php', NULL, 1, NULL, 1);
INSERT INTO admin_navigation VALUES (NULL, 'emails', 'E-Mail Vorlagen', 'config', 'emails.php', NULL, 2, NULL, 1);
INSERT INTO admin_navigation VALUES (NULL, 'configuration', 'Download Options', 'config', 'configuration.php', 13, 1, NULL, 1);
INSERT INTO admin_navigation VALUES (NULL, 'configuration', 'Download Optionen', 'config', 'configuration.php', 13, 2, NULL, 1);
INSERT INTO admin_navigation VALUES (NULL, 'configuration', 'GZip Compression', 'config', 'configuration.php', 14, 1, NULL, 1);
INSERT INTO admin_navigation VALUES (NULL, 'configuration', 'GZip Kompression', 'config', 'configuration.php', 14, 2, NULL, 1);
INSERT INTO admin_navigation VALUES (NULL, 'configuration', 'Sessions Options', 'config', 'configuration.php', 15, 1, NULL, 1);
INSERT INTO admin_navigation VALUES (NULL, 'configuration', 'Sessions Optionen', 'config', 'configuration.php', 15, 2, NULL, 1);
INSERT INTO admin_navigation VALUES (NULL, 'configuration', 'Meta-Tags/Searchengines', 'config', 'configuration.php', 16, 1, NULL, 1);
INSERT INTO admin_navigation VALUES (NULL, 'configuration', 'Meta-Tags / Suchmaschinen', 'config', 'configuration.php', 16, 2, NULL, 1);
INSERT INTO admin_navigation VALUES (NULL, 'configuration', 'Specialmodules', 'config', 'configuration.php', 17, 1, NULL, 1);
INSERT INTO admin_navigation VALUES (NULL, 'configuration', 'Zusatzmodule', 'config', 'configuration.php', 17, 2, NULL, 1);
INSERT INTO admin_navigation VALUES (NULL, 'configuration', 'UST ID', 'config', 'configuration.php', 18, 1, NULL, 1);
INSERT INTO admin_navigation VALUES (NULL, 'configuration', 'UST ID', 'config', 'configuration.php', 18, 2, NULL, 1);
INSERT INTO admin_navigation VALUES (NULL, 'configuration', 'Partner', 'config', 'configuration.php', 19, 1, NULL, 1);
INSERT INTO admin_navigation VALUES (NULL, 'configuration', 'Partner', 'config', 'configuration.php', 19, 2, NULL, 1);
INSERT INTO admin_navigation VALUES (NULL, 'configuration', 'Search Options', 'config', 'configuration.php', 22, 1, NULL, 1);
INSERT INTO admin_navigation VALUES (NULL, 'configuration', 'Such Optionen', 'config', 'configuration.php', 22, 2, NULL, 1);
INSERT INTO admin_navigation VALUES (NULL, 'orders_status', 'Order Status', 'config', 'orders_status.php', NULL, 1, NULL, 1);
INSERT INTO admin_navigation VALUES (NULL, 'orders_status', 'Bestellstatus', 'config', 'orders_status.php', NULL, 2, NULL, 1);
INSERT INTO admin_navigation VALUES (NULL, 'shipping_status', 'Shipping Status', 'config', 'shipping_status.php', NULL, 1, NULL, 1);
INSERT INTO admin_navigation VALUES (NULL, 'shipping_status', 'Lieferstatus', 'config', 'shipping_status.php', NULL, 2, NULL, 1);
INSERT INTO admin_navigation VALUES (NULL, 'products_vpe', 'Packing unit', 'config', 'products_vpe.php', NULL, 1, NULL, 1);
INSERT INTO admin_navigation VALUES (NULL, 'products_vpe', 'Grundpreis Einstellung', 'config', 'products_vpe.php', NULL, 2, NULL, 1);
INSERT INTO admin_navigation VALUES (NULL, 'campaigns', 'Campaigns', 'config', 'campaigns.php', NULL, 1, NULL, 1);
INSERT INTO admin_navigation VALUES (NULL, 'campaigns', 'Kampagnen', 'config', 'campaigns.php', NULL, 2, NULL, 1);
INSERT INTO admin_navigation VALUES (NULL, 'cross_sell_groups', 'Cross-Selling Groups', 'config', 'cross_sell_groups.php', NULL, 1, NULL, 1);
INSERT INTO admin_navigation VALUES (NULL, 'cross_sell_groups', 'Cross-Selling Gruppen', 'config', 'cross_sell_groups.php', NULL, 2, NULL, 1);

INSERT INTO admin_navigation VALUES(NULL, 'comments_orders', 'Kommentarvorlagen', 'customers', 'comments_orders.php', NULL, 2, NULL, 10);
INSERT INTO admin_navigation VALUES(NULL, 'comments_orders', 'Comment Templates', 'customers', 'comments_orders.php', NULL, 1, NULL, 10);
INSERT INTO admin_navigation VALUES(NULL, 'cseo_checkout_sort', 'Sortierung Checkout', 'seo_config', 'cseo_checkout_sort.php', NULL, 2, NULL, 10);
INSERT INTO admin_navigation VALUES(NULL, 'cseo_checkout_sort', 'Sort Checkout', 'seo_config', 'cseo_checkout_sort.php', NULL, 1, NULL, 10);
INSERT INTO admin_navigation VALUES(NULL, 'cseo_main_sort', 'Sortierung Startseite', 'seo_config', 'cseo_main_sort.php', NULL, 2, NULL, 10);
INSERT INTO admin_navigation VALUES(NULL, 'cseo_main_sort', 'Sort Main', 'seo_config', 'cseo_main_sort.php', NULL, 1, NULL, 10);
INSERT INTO admin_navigation VALUES(NULL, 'cseo_logo', 'Logo Manager', 'seo_config', 'cseo_logo.php', NULL, 2, NULL, 11);
INSERT INTO admin_navigation VALUES(NULL, 'cseo_logo', 'Logo Manager', 'seo_config', 'cseo_logo.php', NULL, 1, NULL, 11);
INSERT INTO admin_navigation VALUES(NULL, 'csv_import_export', 'Erweiterter Import/Export', 'tools', 'csv_import_export.php', NULL, 2, NULL, 11);
INSERT INTO admin_navigation VALUES(NULL, 'csv_import_export', 'Advanced Import/Export', 'tools', 'csv_import_export.php', NULL, 1, NULL, 11);
INSERT INTO admin_navigation VALUES(NULL, 'shipping_tracking', 'Versand Tracking', 'config', 'shipping_tracking.php', NULL, 2, NULL, 11);
INSERT INTO admin_navigation VALUES(NULL, 'shipping_tracking', 'Shipping Tracking', 'config', 'shipping_tracking.php', NULL, 1, NULL, 11);
INSERT INTO admin_navigation VALUES(NULL, 'cseo_gallery_manager', 'Slider Manager', 'tools', 'cseo_gallery_manager.php', NULL, 2, NULL, 12);
INSERT INTO admin_navigation VALUES(NULL, 'cseo_gallery_manager', 'Slider Manager', 'tools', 'cseo_gallery_manager.php', NULL, 1, NULL, 12);
INSERT INTO admin_navigation VALUES(NULL, 'cseo_rma', 'Retouren Anfragen', 'customers', 'cseo_rma.php', NULL, 2, NULL, 11);
INSERT INTO admin_navigation VALUES(NULL, 'cseo_rma', 'RMA', 'customers', 'cseo_rma.php', NULL, 1, NULL, 11);
INSERT INTO admin_navigation VALUES (NULL, 'specials_gratis', 'Gratisartikel', 'products', 'specials_gratis.php', NULL, 2, NULL, 5);
INSERT INTO admin_navigation VALUES (NULL, 'specials_gratis', 'Specials-Free', 'products', 'specials_gratis.php', NULL, 1, NULL, 5);

INSERT INTO admin_navigation VALUES (NULL, 'it_recht_kanzlei', 'IT-Rechtskanzlei', 'modules', 'it_recht_kanzlei.php', NULL, 2, NULL, 12);
INSERT INTO admin_navigation VALUES (NULL, 'it_recht_kanzlei', 'IT-Rechtskanzlei', 'modules', 'it_recht_kanzlei.php', NULL, 1, NULL, 12);
