INSERT INTO addon_filenames VALUES (NULL , 'FILENAME_PRODUCTS_PROMOTION', 'products_promotion.php');
INSERT INTO addon_filenames VALUES (NULL , 'FILENAME_CSEO_PRODUCT_EXPORT', 'cseo_product_export.php');
INSERT INTO addon_filenames VALUES (NULL , 'FILENAME_DOWNLOAD_PDF_BILL', 'download_pdf_bill.php');

INSERT INTO addon_languages VALUES (NULL ,'PP_HEADER_TITLE','Produkt Promotion v2.3',2);
INSERT INTO addon_languages VALUES (NULL ,'PP_CONFIG_GLOBAL_ON','Promotion f&uuml;r dieses Produkt aktivieren?',2);
INSERT INTO addon_languages VALUES (NULL ,'PP_CONFIG_PRODUCT_TITLE_ON','Artikelname als Promotion Titel?',2);
INSERT INTO addon_languages VALUES (NULL ,'PP_CONFIG_PRODUCT_DESCRIPTION_ON','Artikelbeschreibung als Promotiontext?',2);
INSERT INTO addon_languages VALUES (NULL ,'PP_TEXT_TITLE','Promotion Titel (max.100 Zeichen)',2);
INSERT INTO addon_languages VALUES (NULL ,'PP_TEXT_IMAGE','Promotion Grafik einfügen',2);
INSERT INTO addon_languages VALUES (NULL ,'PP_TEXT_DELETE','Grafik löschen?',2);
INSERT INTO addon_languages VALUES (NULL ,'PP_TEXT_DESCRIPTION','Promotion Beschreibung/Text',2);
INSERT INTO addon_languages VALUES (NULL ,'PP_TEXT_WARNING', '<b>Sie m&uuml;ssen das Modul noch unter Konfiguration > Zusatzmodule > Produktpromotion aktivieren.</b>',2);
INSERT INTO addon_languages VALUES (NULL ,'MODULE_PRODUCT_PROMOTION_STATUS_TITLE' , 'Produktpromotion aktivieren',2);
INSERT INTO addon_languages VALUES (NULL ,'MODULE_PRODUCT_PROMOTION_STATUS_DESC' , 'Aktivieren Sie diese Funktion, wenn Sie auf der Startseite des Shops ausgew&auml;hlte Produkte besonders hervorheben/promoten m&ouml;chten.<br /> In der Produktmaske k&ouml;nnen Sie Titel, Beschreibung und speziell angefertigte Grafiken zuweisen, sowie Produktanzeige deaktivieren, ohne bestehende Angaben l&ouml;schen zu m&uuml;ssen.',2);
INSERT INTO addon_languages VALUES (NULL ,'PP_HEADER_TITLE','Product Promotion v2.3',1);
INSERT INTO addon_languages VALUES (NULL ,'PP_CONFIG_GLOBAL_ON','Show Promotion for this Product?',1);
INSERT INTO addon_languages VALUES (NULL ,'PP_CONFIG_PRODUCT_TITLE_ON','Promotion Title by Productname?',1);
INSERT INTO addon_languages VALUES (NULL ,'PP_CONFIG_PRODUCT_DESCRIPTION_ON','Promotion Description by Productdescription?',1);
INSERT INTO addon_languages VALUES (NULL ,'PP_TEXT_TITLE','Promotion Title (max.100 Indications)',1);
INSERT INTO addon_languages VALUES (NULL ,'PP_TEXT_IMAGE','Promotion Image',1);
INSERT INTO addon_languages VALUES (NULL ,'PP_TEXT_DELETE','Del Image?',1);
INSERT INTO addon_languages VALUES (NULL ,'PP_TEXT_DESCRIPTION','Promotion Description/Text',1);
INSERT INTO addon_languages VALUES (NULL ,'PP_TEXT_WARNING', '<b>You must enable the module is still under Configuration > Plug-ins > Product Promotion.</b>',1);
INSERT INTO addon_languages VALUES (NULL ,'MODULE_PRODUCT_PROMOTION_STATUS_TITLE' , 'Show Productpromotion',1);
INSERT INTO addon_languages VALUES (NULL ,'MODULE_PRODUCT_PROMOTION_STATUS_DESC' , 'Activate this function, if you particularly promotion on the starting side of the Shops selected products liked. On the product mask you can assign title, description and particularly made diagrams, as well as deactivate product announcement, without having to delete existing data.',1);
INSERT INTO addon_languages VALUES (NULL , 'BOX_COMMENTS_ORDERS', 'Kommentar-Vorlagen', '2');
INSERT INTO addon_languages VALUES (NULL , 'BOX_COMMENTS_ORDERS', 'Comment templates', '1');

INSERT INTO addon_database VALUES (NULL, 'TABLE_BLOG_COMMENT', 'blog_comment');
