#Countries
INSERT INTO countries VALUES (1,'Afghanistan','AF','AFG',1,1);
INSERT INTO countries VALUES (2,'Albania','AL','ALB',1,1);
INSERT INTO countries VALUES (3,'Algeria','DZ','DZA',1,1);
INSERT INTO countries VALUES (4,'American Samoa','AS','ASM',1,1);
INSERT INTO countries VALUES (5,'Andorra','AD','AND',1,1);
INSERT INTO countries VALUES (6,'Angola','AO','AGO',1,1);
INSERT INTO countries VALUES (7,'Anguilla','AI','AIA',1,1);
INSERT INTO countries VALUES (8,'Antarctica','AQ','ATA',1,1);
INSERT INTO countries VALUES (9,'Antigua and Barbuda','AG','ATG',1,1);
INSERT INTO countries VALUES (10,'Argentina','AR','ARG',1,1);
INSERT INTO countries VALUES (11,'Armenia','AM','ARM',1,1);
INSERT INTO countries VALUES (12,'Aruba','AW','ABW',1,1);
INSERT INTO countries VALUES (13,'Australia','AU','AUD',1,1);
INSERT INTO countries VALUES (14,'Austria','AT','AUT',5,1);
INSERT INTO countries VALUES (15,'Azerbaijan','AZ','AZE',1,1);
INSERT INTO countries VALUES (16,'Bahamas','BS','BHS',1,1);
INSERT INTO countries VALUES (17,'Bahrain','BH','BHR',1,1);
INSERT INTO countries VALUES (18,'Bangladesh','BD','BGD',1,1);
INSERT INTO countries VALUES (19,'Barbados','BB','BRB',1,1);
INSERT INTO countries VALUES (20,'Belarus','BY','BLR',1,1);
INSERT INTO countries VALUES (21,'Belgium','BE','BEL',1,1);
INSERT INTO countries VALUES (22,'Belize','BZ','BLZ',1,1);
INSERT INTO countries VALUES (23,'Benin','BJ','BEN',1,1);
INSERT INTO countries VALUES (24,'Bermuda','BM','BMU',1,1);
INSERT INTO countries VALUES (25,'Bhutan','BT','BTN',1,1);
INSERT INTO countries VALUES (26,'Bolivia','BO','BOL',1,1);
INSERT INTO countries VALUES (27,'Bosnia and Herzegowina','BA','BIH',1,1);
INSERT INTO countries VALUES (28,'Botswana','BW','BWA',1,1);
INSERT INTO countries VALUES (29,'Bouvet Island','BV','BVT',1,1);
INSERT INTO countries VALUES (30,'Brazil','BR','BRA',1,1);
INSERT INTO countries VALUES (31,'British Indian Ocean Territory','IO','IOT',1,1);
INSERT INTO countries VALUES (32,'Brunei Darussalam','BN','BRN',1,1);
INSERT INTO countries VALUES (33,'Bulgaria','BG','BGR',1,1);
INSERT INTO countries VALUES (34,'Burkina Faso','BF','BFA',1,1);
INSERT INTO countries VALUES (35,'Burundi','BI','BDI',1,1);
INSERT INTO countries VALUES (36,'Cambodia','KH','KHM',1,1);
INSERT INTO countries VALUES (37,'Cameroon','CM','CMR',1,1);
INSERT INTO countries VALUES (38,'Canada','CA','CAN',1,1);
INSERT INTO countries VALUES (39,'Cape Verde','CV','CPV',1,1);
INSERT INTO countries VALUES (40,'Cayman Islands','KY','CYM',1,1);
INSERT INTO countries VALUES (41,'Central African Republic','CF','CAF',1,1);
INSERT INTO countries VALUES (42,'Chad','TD','TCD',1,1);
INSERT INTO countries VALUES (43,'Chile','CL','CHL',1,1);
INSERT INTO countries VALUES (44,'China','CN','CHN',7,1);
INSERT INTO countries VALUES (45,'Christmas Island','CX','CXR',1,1);
INSERT INTO countries VALUES (46,'Cocos (Keeling) Islands','CC','CCK',1,1);
INSERT INTO countries VALUES (47,'Colombia','CO','COL',1,1);
INSERT INTO countries VALUES (48,'Comoros','KM','COM',1,1);
INSERT INTO countries VALUES (49,'Congo','CG','COG',1,1);
INSERT INTO countries VALUES (50,'Cook Islands','CK','COK',1,1);
INSERT INTO countries VALUES (51,'Costa Rica','CR','CRI',1,1);
INSERT INTO countries VALUES (52,'Cote D\'Ivoire','CI','CIV',1,1);
INSERT INTO countries VALUES (53,'Croatia','HR','HRV',1,1);
INSERT INTO countries VALUES (54,'Cuba','CU','CUB',1,1);
INSERT INTO countries VALUES (55,'Cyprus','CY','CYP',1,1);
INSERT INTO countries VALUES (56,'Czech Republic','CZ','CZE',1,1);
INSERT INTO countries VALUES (57,'Denmark','DK','DNK',1,1);
INSERT INTO countries VALUES (58,'Djibouti','DJ','DJI',1,1);
INSERT INTO countries VALUES (59,'Dominica','DM','DMA',1,1);
INSERT INTO countries VALUES (60,'Dominican Republic','DO','DOM',1,1);
INSERT INTO countries VALUES (61,'East Timor','TP','TMP',1,1);
INSERT INTO countries VALUES (62,'Ecuador','EC','ECU',1,1);
INSERT INTO countries VALUES (63,'Egypt','EG','EGY',1,1);
INSERT INTO countries VALUES (64,'El Salvador','SV','SLV',1,1);
INSERT INTO countries VALUES (65,'Equatorial Guinea','GQ','GNQ',1,1);
INSERT INTO countries VALUES (66,'Eritrea','ER','ERI',1,1);
INSERT INTO countries VALUES (67,'Estonia','EE','EST',1,1);
INSERT INTO countries VALUES (68,'Ethiopia','ET','ETH',1,1);
INSERT INTO countries VALUES (69,'Falkland Islands (Malvinas)','FK','FLK',1,1);
INSERT INTO countries VALUES (70,'Faroe Islands','FO','FRO',1,1);
INSERT INTO countries VALUES (71,'Fiji','FJ','FJI',1,1);
INSERT INTO countries VALUES (72,'Finland','FI','FIN',1,1);
INSERT INTO countries VALUES (73,'France','FR','FRA',1,1);
INSERT INTO countries VALUES (74,'France, Metropolitan','FX','FXX',1,1);
INSERT INTO countries VALUES (75,'French Guiana','GF','GUF',1,1);
INSERT INTO countries VALUES (76,'French Polynesia','PF','PYF',1,1);
INSERT INTO countries VALUES (77,'French Southern Territories','TF','ATF',1,1);
INSERT INTO countries VALUES (78,'Gabon','GA','GAB',1,1);
INSERT INTO countries VALUES (79,'Gambia','GM','GMB',1,1);
INSERT INTO countries VALUES (80,'Georgia','GE','GEO',1,1);
INSERT INTO countries VALUES (81,'Deutschland','DE','DEU',5,1);
INSERT INTO countries VALUES (82,'Ghana','GH','GHA',1,1);
INSERT INTO countries VALUES (83,'Gibraltar','GI','GIB',1,1);
INSERT INTO countries VALUES (84,'Greece','GR','GRC',1,1);
INSERT INTO countries VALUES (85,'Greenland','GL','GRL',1,1);
INSERT INTO countries VALUES (86,'Grenada','GD','GRD',1,1);
INSERT INTO countries VALUES (87,'Guadeloupe','GP','GLP',1,1);
INSERT INTO countries VALUES (88,'Guam','GU','GUM',1,1);
INSERT INTO countries VALUES (89,'Guatemala','GT','GTM',1,1);
INSERT INTO countries VALUES (90,'Guinea','GN','GIN',1,1);
INSERT INTO countries VALUES (91,'Guinea-bissau','GW','GNB',1,1);
INSERT INTO countries VALUES (92,'Guyana','GY','GUY',1,1);
INSERT INTO countries VALUES (93,'Haiti','HT','HTI',1,1);
INSERT INTO countries VALUES (94,'Heard and Mc Donald Islands','HM','HMD',1,1);
INSERT INTO countries VALUES (95,'Honduras','HN','HND',1,1);
INSERT INTO countries VALUES (96,'Hong Kong','HK','HKG',1,1);
INSERT INTO countries VALUES (97,'Hungary','HU','HUN',1,1);
INSERT INTO countries VALUES (98,'Iceland','IS','ISL',1,1);
INSERT INTO countries VALUES (99,'India','IN','IND',1,1);
INSERT INTO countries VALUES (100,'Indonesia','ID','IDN',1,1);
INSERT INTO countries VALUES (101,'Iran (Islamic Republic of)','IR','IRN',1,1);
INSERT INTO countries VALUES (102,'Iraq','IQ','IRQ',1,1);
INSERT INTO countries VALUES (103,'Ireland','IE','IRL',6,1);
INSERT INTO countries VALUES (104,'Israel','IL','ISR',1,1);
INSERT INTO countries VALUES (105,'Italy','IT','ITA',1,1);
INSERT INTO countries VALUES (106,'Jamaica','JM','JAM',1,1);
INSERT INTO countries VALUES (107,'Japan','JP','JPN',1,1);
INSERT INTO countries VALUES (108,'Jordan','JO','JOR',1,1);
INSERT INTO countries VALUES (109,'Kazakhstan','KZ','KAZ',1,1);
INSERT INTO countries VALUES (110,'Kenya','KE','KEN',1,1);
INSERT INTO countries VALUES (111,'Kiribati','KI','KIR',1,1);
INSERT INTO countries VALUES (112,'Korea, Democratic People\'s Republic of','KP','PRK',1,1);
INSERT INTO countries VALUES (113,'Korea, Republic of','KR','KOR',1,1);
INSERT INTO countries VALUES (114,'Kuwait','KW','KWT',1,1);
INSERT INTO countries VALUES (115,'Kyrgyzstan','KG','KGZ',1,1);
INSERT INTO countries VALUES (116,'Lao People\'s Democratic Republic','LA','LAO',1,1);
INSERT INTO countries VALUES (117,'Latvia','LV','LVA',1,1);
INSERT INTO countries VALUES (118,'Lebanon','LB','LBN',1,1);
INSERT INTO countries VALUES (119,'Lesotho','LS','LSO',1,1);
INSERT INTO countries VALUES (120,'Liberia','LR','LBR',1,1);
INSERT INTO countries VALUES (121,'Libyan Arab Jamahiriya','LY','LBY',1,1);
INSERT INTO countries VALUES (122,'Liechtenstein','LI','LIE',1,1);
INSERT INTO countries VALUES (123,'Lithuania','LT','LTU',1,1);
INSERT INTO countries VALUES (124,'Luxembourg','LU','LUX',1,1);
INSERT INTO countries VALUES (125,'Macau','MO','MAC',1,1);
INSERT INTO countries VALUES (126,'Macedonia, The Former Yugoslav Republic of','MK','MKD',1,1);
INSERT INTO countries VALUES (127,'Madagascar','MG','MDG',1,1);
INSERT INTO countries VALUES (128,'Malawi','MW','MWI',1,1);
INSERT INTO countries VALUES (129,'Malaysia','MY','MYS',1,1);
INSERT INTO countries VALUES (130,'Maldives','MV','MDV',1,1);
INSERT INTO countries VALUES (131,'Mali','ML','MLI',1,1);
INSERT INTO countries VALUES (132,'Malta','MT','MLT',1,1);
INSERT INTO countries VALUES (133,'Marshall Islands','MH','MHL',1,1);
INSERT INTO countries VALUES (134,'Martinique','MQ','MTQ',1,1);
INSERT INTO countries VALUES (135,'Mauritania','MR','MRT',1,1);
INSERT INTO countries VALUES (136,'Mauritius','MU','MUS',1,1);
INSERT INTO countries VALUES (137,'Mayotte','YT','MYT',1,1);
INSERT INTO countries VALUES (138,'Mexico','MX','MEX',1,1);
INSERT INTO countries VALUES (139,'Micronesia, Federated States of','FM','FSM',1,1);
INSERT INTO countries VALUES (140,'Moldova, Republic of','MD','MDA',1,1);
INSERT INTO countries VALUES (141,'Monaco','MC','MCO',1,1);
INSERT INTO countries VALUES (142,'Mongolia','MN','MNG',1,1);
INSERT INTO countries VALUES (143,'Montserrat','MS','MSR',1,1);
INSERT INTO countries VALUES (144,'Morocco','MA','MAR',1,1);
INSERT INTO countries VALUES (145,'Mozambique','MZ','MOZ',1,1);
INSERT INTO countries VALUES (146,'Myanmar','MM','MMR',1,1);
INSERT INTO countries VALUES (147,'Namibia','NA','NAM',1,1);
INSERT INTO countries VALUES (148,'Nauru','NR','NRU',1,1);
INSERT INTO countries VALUES (149,'Nepal','NP','NPL',1,1);
INSERT INTO countries VALUES (150,'Netherlands','NL','NLD',1,1);
INSERT INTO countries VALUES (151,'Netherlands Antilles','AN','ANT',1,1);
INSERT INTO countries VALUES (152,'New Caledonia','NC','NCL',1,1);
INSERT INTO countries VALUES (153,'New Zealand','NZ','NZL',1,1);
INSERT INTO countries VALUES (154,'Nicaragua','NI','NIC',1,1);
INSERT INTO countries VALUES (155,'Niger','NE','NER',1,1);
INSERT INTO countries VALUES (156,'Nigeria','NG','NGA',1,1);
INSERT INTO countries VALUES (157,'Niue','NU','NIU',1,1);
INSERT INTO countries VALUES (158,'Norfolk Island','NF','NFK',1,1);
INSERT INTO countries VALUES (159,'Northern Mariana Islands','MP','MNP',1,1);
INSERT INTO countries VALUES (160,'Norway','NO','NOR',1,1);
INSERT INTO countries VALUES (161,'Oman','OM','OMN',1,1);
INSERT INTO countries VALUES (162,'Pakistan','PK','PAK',1,1);
INSERT INTO countries VALUES (163,'Palau','PW','PLW',1,1);
INSERT INTO countries VALUES (164,'Panama','PA','PAN',1,1);
INSERT INTO countries VALUES (165,'Papua New Guinea','PG','PNG',1,1);
INSERT INTO countries VALUES (166,'Paraguay','PY','PRY',1,1);
INSERT INTO countries VALUES (167,'Peru','PE','PER',1,1);
INSERT INTO countries VALUES (168,'Philippines','PH','PHL',1,1);
INSERT INTO countries VALUES (169,'Pitcairn','PN','PCN',1,1);
INSERT INTO countries VALUES (170,'Poland','PL','POL',1,1);
INSERT INTO countries VALUES (171,'Portugal','PT','PRT',1,1);
INSERT INTO countries VALUES (172,'Puerto Rico','PR','PRI',1,1);
INSERT INTO countries VALUES (173,'Qatar','QA','QAT',1,1);
INSERT INTO countries VALUES (174,'Reunion','RE','REU',1,1);
INSERT INTO countries VALUES (175,'Romania','RO','ROM',1,1);
INSERT INTO countries VALUES (176,'Russian Federation','RU','RUS',1,1);
INSERT INTO countries VALUES (177,'Rwanda','RW','RWA',1,1);
INSERT INTO countries VALUES (178,'Saint Kitts and Nevis','KN','KNA',1,1);
INSERT INTO countries VALUES (179,'Saint Lucia','LC','LCA',1,1);
INSERT INTO countries VALUES (180,'Saint Vincent and the Grenadines','VC','VCT',1,1);
INSERT INTO countries VALUES (181,'Samoa','WS','WSM',1,1);
INSERT INTO countries VALUES (182,'San Marino','SM','SMR',1,1);
INSERT INTO countries VALUES (183,'Sao Tome and Principe','ST','STP',1,1);
INSERT INTO countries VALUES (184,'Saudi Arabia','SA','SAU',1,1);
INSERT INTO countries VALUES (185,'Senegal','SN','SEN',1,1);
INSERT INTO countries VALUES (186,'Seychelles','SC','SYC',1,1);
INSERT INTO countries VALUES (187,'Sierra Leone','SL','SLE',1,1);
INSERT INTO countries VALUES (188,'Singapore','SG','SGP', '4','1');
INSERT INTO countries VALUES (189,'Slovakia (Slovak Republic)','SK','SVK',1,1);
INSERT INTO countries VALUES (190,'Slovenia','SI','SVN',1,1);
INSERT INTO countries VALUES (191,'Solomon Islands','SB','SLB',1,1);
INSERT INTO countries VALUES (192,'Somalia','SO','SOM',1,1);
INSERT INTO countries VALUES (193,'South Africa','ZA','ZAF',1,1);
INSERT INTO countries VALUES (194,'South Georgia and the South Sandwich Islands','GS','SGS',1,1);
INSERT INTO countries VALUES (195,'Spain','ES','ESP','3','1');
INSERT INTO countries VALUES (196,'Sri Lanka','LK','LKA',1,1);
INSERT INTO countries VALUES (197,'St. Helena','SH','SHN',1,1);
INSERT INTO countries VALUES (198,'St. Pierre and Miquelon','PM','SPM',1,1);
INSERT INTO countries VALUES (199,'Sudan','SD','SDN',1,1);
INSERT INTO countries VALUES (200,'Suriname','SR','SUR',1,1);
INSERT INTO countries VALUES (201,'Svalbard and Jan Mayen Islands','SJ','SJM',1,1);
INSERT INTO countries VALUES (202,'Swaziland','SZ','SWZ',1,1);
INSERT INTO countries VALUES (203,'Sweden','SE','SWE',1,1);
INSERT INTO countries VALUES (204,'Switzerland','CH','CHE',5,1);
INSERT INTO countries VALUES (205,'Syrian Arab Republic','SY','SYR',1,1);
INSERT INTO countries VALUES (206,'Taiwan','TW','TWN',6,1);
INSERT INTO countries VALUES (207,'Tajikistan','TJ','TJK',1,1);
INSERT INTO countries VALUES (208,'Tanzania, United Republic of','TZ','TZA',1,1);
INSERT INTO countries VALUES (209,'Thailand','TH','THA',1,1);
INSERT INTO countries VALUES (210,'Togo','TG','TGO',1,1);
INSERT INTO countries VALUES (211,'Tokelau','TK','TKL',1,1);
INSERT INTO countries VALUES (212,'Tonga','TO','TON',1,1);
INSERT INTO countries VALUES (213,'Trinidad and Tobago','TT','TTO',1,1);
INSERT INTO countries VALUES (214,'Tunisia','TN','TUN',1,1);
INSERT INTO countries VALUES (215,'Turkey','TR','TUR',1,1);
INSERT INTO countries VALUES (216,'Turkmenistan','TM','TKM',1,1);
INSERT INTO countries VALUES (217,'Turks and Caicos Islands','TC','TCA',1,1);
INSERT INTO countries VALUES (218,'Tuvalu','TV','TUV',1,1);
INSERT INTO countries VALUES (219,'Uganda','UG','UGA',1,1);
INSERT INTO countries VALUES (220,'Ukraine','UA','UKR',1,1);
INSERT INTO countries VALUES (221,'United Arab Emirates','AE','ARE',1,1);
INSERT INTO countries VALUES (222,'United Kingdom','GB','GBR',8,1);
INSERT INTO countries VALUES (223,'United States','US','USA', '2','1');
INSERT INTO countries VALUES (224,'United States Minor Outlying Islands','UM','UMI',1,1);
INSERT INTO countries VALUES (225,'Uruguay','UY','URY',1,1);
INSERT INTO countries VALUES (226,'Uzbekistan','UZ','UZB',1,1);
INSERT INTO countries VALUES (227,'Vanuatu','VU','VUT',1,1);
INSERT INTO countries VALUES (228,'Vatican City State (Holy See)','VA','VAT',1,1);
INSERT INTO countries VALUES (229,'Venezuela','VE','VEN',1,1);
INSERT INTO countries VALUES (230,'Viet Nam','VN','VNM',1,1);
INSERT INTO countries VALUES (231,'Virgin Islands (British)','VG','VGB',1,1);
INSERT INTO countries VALUES (232,'Virgin Islands (U.S.)','VI','VIR',1,1);
INSERT INTO countries VALUES (233,'Wallis and Futuna Islands','WF','WLF',1,1);
INSERT INTO countries VALUES (234,'Western Sahara','EH','ESH',1,1);
INSERT INTO countries VALUES (235,'Yemen','YE','YEM',1,1);
INSERT INTO countries VALUES (237,'Zaire','ZR','ZAR',1,1);
INSERT INTO countries VALUES (238,'Zambia','ZM','ZMB',1,1);
INSERT INTO countries VALUES (239,'Zimbabwe','ZW','ZWE',1,1);
INSERT INTO countries VALUES (240,'Serbia','RS','SRB',1,1);
INSERT INTO countries VALUES (241,'Montenegro','ME','MNE',1,1);

# USA
INSERT INTO zones VALUES (1,223,'AL','Alabama');
INSERT INTO zones VALUES (2,223,'AK','Alaska');
INSERT INTO zones VALUES (3,223,'AS','American Samoa');
INSERT INTO zones VALUES (4,223,'AZ','Arizona');
INSERT INTO zones VALUES (5,223,'AR','Arkansas');
INSERT INTO zones VALUES (6,223,'AF','Armed Forces Africa');
INSERT INTO zones VALUES (7,223,'AA','Armed Forces Americas');
INSERT INTO zones VALUES (8,223,'AC','Armed Forces Canada');
INSERT INTO zones VALUES (9,223,'AE','Armed Forces Europe');
INSERT INTO zones VALUES (10,223,'AM','Armed Forces Middle East');
INSERT INTO zones VALUES (11,223,'AP','Armed Forces Pacific');
INSERT INTO zones VALUES (12,223,'CA','California');
INSERT INTO zones VALUES (13,223,'CO','Colorado');
INSERT INTO zones VALUES (14,223,'CT','Connecticut');
INSERT INTO zones VALUES (15,223,'DE','Delaware');
INSERT INTO zones VALUES (16,223,'DC','District of Columbia');
INSERT INTO zones VALUES (17,223,'FM','Federated States Of Micronesia');
INSERT INTO zones VALUES (18,223,'FL','Florida');
INSERT INTO zones VALUES (19,223,'GA','Georgia');
INSERT INTO zones VALUES (20,223,'GU','Guam');
INSERT INTO zones VALUES (21,223,'HI','Hawaii');
INSERT INTO zones VALUES (22,223,'ID','Idaho');
INSERT INTO zones VALUES (23,223,'IL','Illinois');
INSERT INTO zones VALUES (24,223,'IN','Indiana');
INSERT INTO zones VALUES (25,223,'IA','Iowa');
INSERT INTO zones VALUES (26,223,'KS','Kansas');
INSERT INTO zones VALUES (27,223,'KY','Kentucky');
INSERT INTO zones VALUES (28,223,'LA','Louisiana');
INSERT INTO zones VALUES (29,223,'ME','Maine');
INSERT INTO zones VALUES (30,223,'MH','Marshall Islands');
INSERT INTO zones VALUES (31,223,'MD','Maryland');
INSERT INTO zones VALUES (32,223,'MA','Massachusetts');
INSERT INTO zones VALUES (33,223,'MI','Michigan');
INSERT INTO zones VALUES (34,223,'MN','Minnesota');
INSERT INTO zones VALUES (35,223,'MS','Mississippi');
INSERT INTO zones VALUES (36,223,'MO','Missouri');
INSERT INTO zones VALUES (37,223,'MT','Montana');
INSERT INTO zones VALUES (38,223,'NE','Nebraska');
INSERT INTO zones VALUES (39,223,'NV','Nevada');
INSERT INTO zones VALUES (40,223,'NH','New Hampshire');
INSERT INTO zones VALUES (41,223,'NJ','New Jersey');
INSERT INTO zones VALUES (42,223,'NM','New Mexico');
INSERT INTO zones VALUES (43,223,'NY','New York');
INSERT INTO zones VALUES (44,223,'NC','North Carolina');
INSERT INTO zones VALUES (45,223,'ND','North Dakota');
INSERT INTO zones VALUES (46,223,'MP','Northern Mariana Islands');
INSERT INTO zones VALUES (47,223,'OH','Ohio');
INSERT INTO zones VALUES (48,223,'OK','Oklahoma');
INSERT INTO zones VALUES (49,223,'OR','Oregon');
INSERT INTO zones VALUES (50,223,'PW','Palau');
INSERT INTO zones VALUES (51,223,'PA','Pennsylvania');
INSERT INTO zones VALUES (52,223,'PR','Puerto Rico');
INSERT INTO zones VALUES (53,223,'RI','Rhode Island');
INSERT INTO zones VALUES (54,223,'SC','South Carolina');
INSERT INTO zones VALUES (55,223,'SD','South Dakota');
INSERT INTO zones VALUES (56,223,'TN','Tennessee');
INSERT INTO zones VALUES (57,223,'TX','Texas');
INSERT INTO zones VALUES (58,223,'UT','Utah');
INSERT INTO zones VALUES (59,223,'VT','Vermont');
INSERT INTO zones VALUES (60,223,'VI','Virgin Islands');
INSERT INTO zones VALUES (61,223,'VA','Virginia');
INSERT INTO zones VALUES (62,223,'WA','Washington');
INSERT INTO zones VALUES (63,223,'WV','West Virginia');
INSERT INTO zones VALUES (64,223,'WI','Wisconsin');
INSERT INTO zones VALUES (65,223,'WY','Wyoming');

# Canada
INSERT INTO zones VALUES (66,38,'AB','Alberta');
INSERT INTO zones VALUES (67,38,'BC','British Columbia');
INSERT INTO zones VALUES (68,38,'MB','Manitoba');
INSERT INTO zones VALUES (69,38,'NF','Newfoundland');
INSERT INTO zones VALUES (70,38,'NB','New Brunswick');
INSERT INTO zones VALUES (71,38,'NS','Nova Scotia');
INSERT INTO zones VALUES (72,38,'NT','Northwest Territories');
INSERT INTO zones VALUES (73,38,'NU','Nunavut');
INSERT INTO zones VALUES (74,38,'ON','Ontario');
INSERT INTO zones VALUES (75,38,'PE','Prince Edward Island');
INSERT INTO zones VALUES (76,38,'QC','Quebec');
INSERT INTO zones VALUES (77,38,'SK','Saskatchewan');
INSERT INTO zones VALUES (78,38,'YT','Yukon Territory');

# Germany
INSERT INTO zones VALUES (79,81,'NI','Niedersachsen');
INSERT INTO zones VALUES (80,81,'BW','Baden-Württemberg');
INSERT INTO zones VALUES (81,81,'BY','Bayern');
INSERT INTO zones VALUES (82,81,'BE','Berlin');
INSERT INTO zones VALUES (83,81,'BR','Brandenburg');
INSERT INTO zones VALUES (84,81,'HB','Bremen');
INSERT INTO zones VALUES (85,81,'HH','Hamburg');
INSERT INTO zones VALUES (86,81,'HE','Hessen');
INSERT INTO zones VALUES (87,81,'MV','Mecklenburg-Vorpommern');
INSERT INTO zones VALUES (88,81,'NW','Nordrhein-Westfalen');
INSERT INTO zones VALUES (89,81,'RP','Rheinland-Pfalz');
INSERT INTO zones VALUES (90,81,'SL','Saarland');
INSERT INTO zones VALUES (91,81,'SN','Sachsen');
INSERT INTO zones VALUES (92,81,'ST','Sachsen-Anhalt');
INSERT INTO zones VALUES (93,81,'SH','Schleswig-Holstein');
INSERT INTO zones VALUES (94,81,'TH','Thüringen');

# Austria
INSERT INTO zones VALUES (95,14,'WI','Wien');
INSERT INTO zones VALUES (96,14,'NO','Niederösterreich');
INSERT INTO zones VALUES (97,14,'OO','Oberösterreich');
INSERT INTO zones VALUES (98,14,'SB','Salzburg');
INSERT INTO zones VALUES (99,14,'KN','Kärnten');
INSERT INTO zones VALUES (100,14,'ST','Steiermark');
INSERT INTO zones VALUES (101,14,'TI','Tirol');
INSERT INTO zones VALUES (102,14,'BL','Burgenland');
INSERT INTO zones VALUES (103,14,'VB','Voralberg');

# Swizterland
INSERT INTO zones VALUES (104,204,'AG','Aargau');
INSERT INTO zones VALUES (105,204,'AI','Appenzell Innerrhoden');
INSERT INTO zones VALUES (106,204,'AR','Appenzell Ausserrhoden');
INSERT INTO zones VALUES (107,204,'BE','Bern');
INSERT INTO zones VALUES (108,204,'BL','Basel-Landschaft');
INSERT INTO zones VALUES (109,204,'BS','Basel-Stadt');
INSERT INTO zones VALUES (110,204,'FR','Freiburg');
INSERT INTO zones VALUES (111,204,'GE','Genf');
INSERT INTO zones VALUES (112,204,'GL','Glarus');
INSERT INTO zones VALUES (113,204,'JU','Graubünden');
INSERT INTO zones VALUES (114,204,'JU','Jura');
INSERT INTO zones VALUES (115,204,'LU','Luzern');
INSERT INTO zones VALUES (116,204,'NE','Neuenburg');
INSERT INTO zones VALUES (117,204,'NW','Nidwalden');
INSERT INTO zones VALUES (118,204,'OW','Obwalden');
INSERT INTO zones VALUES (119,204,'SG','St. Gallen');
INSERT INTO zones VALUES (120,204,'SH','Schaffhausen');
INSERT INTO zones VALUES (121,204,'SO','Solothurn');
INSERT INTO zones VALUES (122,204,'SZ','Schwyz');
INSERT INTO zones VALUES (123,204,'TG','Thurgau');
INSERT INTO zones VALUES (124,204,'TI','Tessin');
INSERT INTO zones VALUES (125,204,'UR','Uri');
INSERT INTO zones VALUES (126,204,'VD','Waadt');
INSERT INTO zones VALUES (127,204,'VS','Wallis');
INSERT INTO zones VALUES (128,204,'ZG','Zug');
INSERT INTO zones VALUES (129,204,'ZH','Zürich');

# Spain
INSERT INTO zones VALUES (130,195,'A Coruña','A Coruña');
INSERT INTO zones VALUES (131,195,'Alava','Alava');
INSERT INTO zones VALUES (132,195,'Albacete','Albacete');
INSERT INTO zones VALUES (133,195,'Alicante','Alicante');
INSERT INTO zones VALUES (134,195,'Almeria','Almeria');
INSERT INTO zones VALUES (135,195,'Asturias','Asturias');
INSERT INTO zones VALUES (136,195,'Avila','Avila');
INSERT INTO zones VALUES (137,195,'Badajoz','Badajoz');
INSERT INTO zones VALUES (138,195,'Baleares','Baleares');
INSERT INTO zones VALUES (139,195,'Barcelona','Barcelona');
INSERT INTO zones VALUES (140,195,'Burgos','Burgos');
INSERT INTO zones VALUES (141,195,'Caceres','Caceres');
INSERT INTO zones VALUES (142,195,'Cadiz','Cadiz');
INSERT INTO zones VALUES (143,195,'Cantabria','Cantabria');
INSERT INTO zones VALUES (144,195,'Castellon','Castellon');
INSERT INTO zones VALUES (145,195,'Ceuta','Ceuta');
INSERT INTO zones VALUES (146,195,'Ciudad Real','Ciudad Real');
INSERT INTO zones VALUES (147,195,'Cordoba','Cordoba');
INSERT INTO zones VALUES (148,195,'Cuenca','Cuenca');
INSERT INTO zones VALUES (149,195,'Girona','Girona');
INSERT INTO zones VALUES (150,195,'Granada','Granada');
INSERT INTO zones VALUES (151,195,'Guadalajara','Guadalajara');
INSERT INTO zones VALUES (152,195,'Guipuzcoa','Guipuzcoa');
INSERT INTO zones VALUES (153,195,'Huelva','Huelva');
INSERT INTO zones VALUES (154,195,'Huesca','Huesca');
INSERT INTO zones VALUES (155,195,'Jaen','Jaen');
INSERT INTO zones VALUES (156,195,'La Rioja','La Rioja');
INSERT INTO zones VALUES (157,195,'Las Palmas','Las Palmas');
INSERT INTO zones VALUES (158,195,'Leon','Leon');
INSERT INTO zones VALUES (159,195,'Lleida','Lleida');
INSERT INTO zones VALUES (160,195,'Lugo','Lugo');
INSERT INTO zones VALUES (161,195,'Madrid','Madrid');
INSERT INTO zones VALUES (162,195,'Malaga','Malaga');
INSERT INTO zones VALUES (163,195,'Melilla','Melilla');
INSERT INTO zones VALUES (164,195,'Murcia','Murcia');
INSERT INTO zones VALUES (165,195,'Navarra','Navarra');
INSERT INTO zones VALUES (166,195,'Ourense','Ourense');
INSERT INTO zones VALUES (167,195,'Palencia','Palencia');
INSERT INTO zones VALUES (168,195,'Pontevedra','Pontevedra');
INSERT INTO zones VALUES (169,195,'Salamanca','Salamanca');
INSERT INTO zones VALUES (170,195,'Santa Cruz de Tenerife','Santa Cruz de Tenerife');
INSERT INTO zones VALUES (171,195,'Segovia','Segovia');
INSERT INTO zones VALUES (172,195,'Sevilla','Sevilla');
INSERT INTO zones VALUES (173,195,'Soria','Soria');
INSERT INTO zones VALUES (174,195,'Tarragona','Tarragona');
INSERT INTO zones VALUES (175,195,'Teruel','Teruel');
INSERT INTO zones VALUES (176,195,'Toledo','Toledo');
INSERT INTO zones VALUES (177,195,'Valencia','Valencia');
INSERT INTO zones VALUES (178,195,'Valladolid','Valladolid');
INSERT INTO zones VALUES (179,195,'Vizcaya','Vizcaya');
INSERT INTO zones VALUES (180,195,'Zamora','Zamora');
INSERT INTO zones VALUES (181,195,'Zaragoza','Zaragoza');

#Australia
INSERT INTO zones VALUES (182,13,'NSW','New South Wales');
INSERT INTO zones VALUES (183,13,'VIC','Victoria');
INSERT INTO zones VALUES (184,13,'QLD','Queensland');
INSERT INTO zones VALUES (185,13,'NT','Northern Territory');
INSERT INTO zones VALUES (186,13,'WA','Western Australia');
INSERT INTO zones VALUES (187,13,'SA','South Australia');
INSERT INTO zones VALUES (188,13,'TAS','Tasmania');
INSERT INTO zones VALUES (189,13,'ACT','Australian Capital Territory');

#New Zealand
INSERT INTO zones VALUES (190,153,'Northland','Northland');
INSERT INTO zones VALUES (191,153,'Auckland','Auckland');
INSERT INTO zones VALUES (192,153,'Waikato','Waikato');
INSERT INTO zones VALUES (193,153,'Bay of Plenty','Bay of Plenty');
INSERT INTO zones VALUES (194,153,'Gisborne','Gisborne');
INSERT INTO zones VALUES (195,153,'Hawkes Bay','Hawkes Bay');
INSERT INTO zones VALUES (196,153,'Taranaki','Taranaki');
INSERT INTO zones VALUES (197,153,'Manawatu-Wanganui','Manawatu-Wanganui');
INSERT INTO zones VALUES (198,153,'Wellington','Wellington');
INSERT INTO zones VALUES (199,153,'West Coast','West Coast');
INSERT INTO zones VALUES (200,153,'Canterbury','Canterbury');
INSERT INTO zones VALUES (201,153,'Otago','Otago');
INSERT INTO zones VALUES (202,153,'Southland','Southland');
INSERT INTO zones VALUES (203,153,'Tasman','Tasman');
INSERT INTO zones VALUES (204,153,'Nelson','Nelson');
INSERT INTO zones VALUES (205,153,'Marlborough','Marlborough');

#Brazil
INSERT INTO zones VALUES ('',30,'SP','São Paulo');
INSERT INTO zones VALUES ('',30,'RJ','Rio de Janeiro');
INSERT INTO zones VALUES ('',30,'PE','Pernanbuco');
INSERT INTO zones VALUES ('',30,'BA','Bahia');
INSERT INTO zones VALUES ('',30,'AM','Amazonas');
INSERT INTO zones VALUES ('',30,'MG','Minas Gerais');
INSERT INTO zones VALUES ('',30,'ES','Espirito Santo');
INSERT INTO zones VALUES ('',30,'RS','Rio Grande do Sul');
INSERT INTO zones VALUES ('',30,'PR','Paraná');
INSERT INTO zones VALUES ('',30,'SC','Santa Catarina');
INSERT INTO zones VALUES ('',30,'RG','Rio Grande do Norte');
INSERT INTO zones VALUES ('',30,'MS','Mato Grosso do Sul');
INSERT INTO zones VALUES ('',30,'MT','Mato Grosso');
INSERT INTO zones VALUES ('',30,'GO','Goias');
INSERT INTO zones VALUES ('',30,'TO','Tocantins');
INSERT INTO zones VALUES ('',30,'DF','Distrito Federal');
INSERT INTO zones VALUES ('',30,'RO','Rondonia');
INSERT INTO zones VALUES ('',30,'AC','Acre');
INSERT INTO zones VALUES ('',30,'AP','Amapa');
INSERT INTO zones VALUES ('',30,'RO','Roraima');
INSERT INTO zones VALUES ('',30,'AL','Alagoas');
INSERT INTO zones VALUES ('',30,'CE','Ceará');
INSERT INTO zones VALUES ('',30,'MA','Maranhão');
INSERT INTO zones VALUES ('',30,'PA','Pará');
INSERT INTO zones VALUES ('',30,'PB','Paraíba');
INSERT INTO zones VALUES ('',30,'PI','Piauí');
INSERT INTO zones VALUES ('',30,'SE','Sergipe');

#Chile
INSERT INTO zones VALUES ('',43,'I','I Región de Tarapacá');
INSERT INTO zones VALUES ('',43,'II','II Región de Antofagasta');
INSERT INTO zones VALUES ('',43,'III','III Región de Atacama');
INSERT INTO zones VALUES ('',43,'IV','IV Región de Coquimbo');
INSERT INTO zones VALUES ('',43,'V','V Región de Valaparaíso');
INSERT INTO zones VALUES ('',43,'RM','Región Metropolitana');
INSERT INTO zones VALUES ('',43,'VI','VI Región de L. B. O´higgins');
INSERT INTO zones VALUES ('',43,'VII','VII Región del Maule');
INSERT INTO zones VALUES ('',43,'VIII','VIII Región del Bío Bío');
INSERT INTO zones VALUES ('',43,'IX','IX Región de la Araucanía');
INSERT INTO zones VALUES ('',43,'X','X Región de los Lagos');
INSERT INTO zones VALUES ('',43,'XI','XI Región de Aysén');
INSERT INTO zones VALUES ('',43,'XII','XII Región de Magallanes');

#Columbia
INSERT INTO zones VALUES ('',47,'AMA','Amazonas');
INSERT INTO zones VALUES ('',47,'ANT','Antioquia');
INSERT INTO zones VALUES ('',47,'ARA','Arauca');
INSERT INTO zones VALUES ('',47,'ATL','Atlantico');
INSERT INTO zones VALUES ('',47,'BOL','Bolivar');
INSERT INTO zones VALUES ('',47,'BOY','Boyaca');
INSERT INTO zones VALUES ('',47,'CAL','Caldas');
INSERT INTO zones VALUES ('',47,'CAQ','Caqueta');
INSERT INTO zones VALUES ('',47,'CAS','Casanare');
INSERT INTO zones VALUES ('',47,'CAU','Cauca');
INSERT INTO zones VALUES ('',47,'CES','Cesar');
INSERT INTO zones VALUES ('',47,'CHO','Choco');
INSERT INTO zones VALUES ('',47,'COR','Cordoba');
INSERT INTO zones VALUES ('',47,'CUN','Cundinamarca');
INSERT INTO zones VALUES ('',47,'HUI','Huila');
INSERT INTO zones VALUES ('',47,'GUA','Guainia');
INSERT INTO zones VALUES ('',47,'GUA','Guajira');
INSERT INTO zones VALUES ('',47,'GUV','Guaviare');
INSERT INTO zones VALUES ('',47,'MAG','Magdalena');
INSERT INTO zones VALUES ('',47,'MET','Meta');
INSERT INTO zones VALUES ('',47,'NAR','Narino');
INSERT INTO zones VALUES ('',47,'NDS','Norte de Santander');
INSERT INTO zones VALUES ('',47,'PUT','Putumayo');
INSERT INTO zones VALUES ('',47,'QUI','Quindio');
INSERT INTO zones VALUES ('',47,'RIS','Risaralda');
INSERT INTO zones VALUES ('',47,'SAI','San Andres Islas');
INSERT INTO zones VALUES ('',47,'SAN','Santander');
INSERT INTO zones VALUES ('',47,'SUC','Sucre');
INSERT INTO zones VALUES ('',47,'TOL','Tolima');
INSERT INTO zones VALUES ('',47,'VAL','Valle');
INSERT INTO zones VALUES ('',47,'VAU','Vaupes');
INSERT INTO zones VALUES ('',47,'VIC','Vichada');

#France
INSERT INTO zones VALUES ('',73,'Et','Etranger');
INSERT INTO zones VALUES ('',73,'01','Ain');
INSERT INTO zones VALUES ('',73,'02','Aisne');
INSERT INTO zones VALUES ('',73,'03','Allier');
INSERT INTO zones VALUES ('',73,'04','Alpes de Haute Provence');
INSERT INTO zones VALUES ('',73,'05','Hautes-Alpes');
INSERT INTO zones VALUES ('',73,'06','Alpes Maritimes');
INSERT INTO zones VALUES ('',73,'07','Ardèche');
INSERT INTO zones VALUES ('',73,'08','Ardennes');
INSERT INTO zones VALUES ('',73,'09','Ariège');
INSERT INTO zones VALUES ('',73,'10','Aube');
INSERT INTO zones VALUES ('',73,'11','Aude');
INSERT INTO zones VALUES ('',73,'12','Aveyron');
INSERT INTO zones VALUES ('',73,'13','Bouches-du-Rhône');
INSERT INTO zones VALUES ('',73,'14','Calvados');
INSERT INTO zones VALUES ('',73,'15','Cantal');
INSERT INTO zones VALUES ('',73,'16','Charente');
INSERT INTO zones VALUES ('',73,'17','Charente Maritime');
INSERT INTO zones VALUES ('',73,'18','Cher');
INSERT INTO zones VALUES ('',73,'19','Corrèze');
INSERT INTO zones VALUES ('',73,'2A','Corse du Sud');
INSERT INTO zones VALUES ('',73,'2B','Haute Corse');
INSERT INTO zones VALUES ('',73,'21','Côte-d\'Or');
INSERT INTO zones VALUES ('',73,'22','Côtes-d\'Armor');
INSERT INTO zones VALUES ('',73,'23','Creuse');
INSERT INTO zones VALUES ('',73,'24','Dordogne');
INSERT INTO zones VALUES ('',73,'25','Doubs');
INSERT INTO zones VALUES ('',73,'26','Drôme');
INSERT INTO zones VALUES ('',73,'27','Eure');
INSERT INTO zones VALUES ('',73,'28','Eure et Loir');
INSERT INTO zones VALUES ('',73,'29','Finistère');
INSERT INTO zones VALUES ('',73,'30','Gard');
INSERT INTO zones VALUES ('',73,'31','Haute Garonne');
INSERT INTO zones VALUES ('',73,'32','Gers');
INSERT INTO zones VALUES ('',73,'33','Gironde');
INSERT INTO zones VALUES ('',73,'34','Hérault');
INSERT INTO zones VALUES ('',73,'35','Ille et Vilaine');
INSERT INTO zones VALUES ('',73,'36','Indre');
INSERT INTO zones VALUES ('',73,'37','Indre et Loire');
INSERT INTO zones VALUES ('',73,'38','Isère');
INSERT INTO zones VALUES ('',73,'39','Jura');
INSERT INTO zones VALUES ('',73,'40','Landes');
INSERT INTO zones VALUES ('',73,'41','Loir et Cher');
INSERT INTO zones VALUES ('',73,'42','Loire');
INSERT INTO zones VALUES ('',73,'43','Haute Loire');
INSERT INTO zones VALUES ('',73,'44','Loire Atlantique');
INSERT INTO zones VALUES ('',73,'45','Loiret');
INSERT INTO zones VALUES ('',73,'46','Lot');
INSERT INTO zones VALUES ('',73,'47','Lot et Garonne');
INSERT INTO zones VALUES ('',73,'48','Lozère');
INSERT INTO zones VALUES ('',73,'49','Maine et Loire');
INSERT INTO zones VALUES ('',73,'50','Manche');
INSERT INTO zones VALUES ('',73,'51','Marne');
INSERT INTO zones VALUES ('',73,'52','Haute Marne');
INSERT INTO zones VALUES ('',73,'53','Mayenne');
INSERT INTO zones VALUES ('',73,'54','Meurthe et Moselle');
INSERT INTO zones VALUES ('',73,'55','Meuse');
INSERT INTO zones VALUES ('',73,'56','Morbihan');
INSERT INTO zones VALUES ('',73,'57','Moselle');
INSERT INTO zones VALUES ('',73,'58','Nièvre');
INSERT INTO zones VALUES ('',73,'59','Nord');
INSERT INTO zones VALUES ('',73,'60','Oise');
INSERT INTO zones VALUES ('',73,'61','Orne');
INSERT INTO zones VALUES ('',73,'62','Pas de Calais');
INSERT INTO zones VALUES ('',73,'63','Puy-de-Dôme');
INSERT INTO zones VALUES ('',73,'64','Pyrénées-Atlantiques');
INSERT INTO zones VALUES ('',73,'65','Hautes-Pyrénées');
INSERT INTO zones VALUES ('',73,'66','Pyrénées-Orientales');
INSERT INTO zones VALUES ('',73,'67','Bas Rhin');
INSERT INTO zones VALUES ('',73,'68','Haut Rhin');
INSERT INTO zones VALUES ('',73,'69','Rhône');
INSERT INTO zones VALUES ('',73,'70','Haute-Saône');
INSERT INTO zones VALUES ('',73,'71','Saône-et-Loire');
INSERT INTO zones VALUES ('',73,'72','Sarthe');
INSERT INTO zones VALUES ('',73,'73','Savoie');
INSERT INTO zones VALUES ('',73,'74','Haute Savoie');
INSERT INTO zones VALUES ('',73,'75','Paris');
INSERT INTO zones VALUES ('',73,'76','Seine Maritime');
INSERT INTO zones VALUES ('',73,'77','Seine et Marne');
INSERT INTO zones VALUES ('',73,'78','Yvelines');
INSERT INTO zones VALUES ('',73,'79','Deux-Sèvres');
INSERT INTO zones VALUES ('',73,'80','Somme');
INSERT INTO zones VALUES ('',73,'81','Tarn');
INSERT INTO zones VALUES ('',73,'82','Tarn et Garonne');
INSERT INTO zones VALUES ('',73,'83','Var');
INSERT INTO zones VALUES ('',73,'84','Vaucluse');
INSERT INTO zones VALUES ('',73,'85','Vendée');
INSERT INTO zones VALUES ('',73,'86','Vienne');
INSERT INTO zones VALUES ('',73,'87','Haute Vienne');
INSERT INTO zones VALUES ('',73,'88','Vosges');
INSERT INTO zones VALUES ('',73,'89','Yonne');
INSERT INTO zones VALUES ('',73,'90','Territoire de Belfort');
INSERT INTO zones VALUES ('',73,'91','Essonne');
INSERT INTO zones VALUES ('',73,'92','Hauts de Seine');
INSERT INTO zones VALUES ('',73,'93','Seine St-Denis');
INSERT INTO zones VALUES ('',73,'94','Val de Marne');
INSERT INTO zones VALUES ('',73,'95','Val d\'Oise');
INSERT INTO zones VALUES ('',73,'971 (DOM)','Guadeloupe');
INSERT INTO zones VALUES ('',73,'972 (DOM)','Martinique');
INSERT INTO zones VALUES ('',73,'973 (DOM)','Guyane');
INSERT INTO zones VALUES ('',73,'974 (DOM)','Saint Denis');
INSERT INTO zones VALUES ('',73,'975 (DOM)','St-Pierre de Miquelon');
INSERT INTO zones VALUES ('',73,'976 (TOM)','Mayotte');
INSERT INTO zones VALUES ('',73,'984 (TOM)','Terres australes et Antartiques françaises');
INSERT INTO zones VALUES ('',73,'985 (TOM)','Nouvelle Calédonie');
INSERT INTO zones VALUES ('',73,'986 (TOM)','Wallis et Futuna');
INSERT INTO zones VALUES ('',73,'987 (TOM)','Polynésie française');

#India
INSERT INTO zones VALUES ('',99,'DL','Delhi');
INSERT INTO zones VALUES ('',99,'MH','Maharashtra');
INSERT INTO zones VALUES ('',99,'TN','Tamil Nadu');
INSERT INTO zones VALUES ('',99,'KL','Kerala');
INSERT INTO zones VALUES ('',99,'AP','Andhra Pradesh');
INSERT INTO zones VALUES ('',99,'KA','Karnataka');
INSERT INTO zones VALUES ('',99,'GA','Goa');
INSERT INTO zones VALUES ('',99,'MP','Madhya Pradesh');
INSERT INTO zones VALUES ('',99,'PY','Pondicherry');
INSERT INTO zones VALUES ('',99,'GJ','Gujarat');
INSERT INTO zones VALUES ('',99,'OR','Orrisa');
INSERT INTO zones VALUES ('',99,'CA','Chhatisgarh');
INSERT INTO zones VALUES ('',99,'JH','Jharkhand');
INSERT INTO zones VALUES ('',99,'BR','Bihar');
INSERT INTO zones VALUES ('',99,'WB','West Bengal');
INSERT INTO zones VALUES ('',99,'UP','Uttar Pradesh');
INSERT INTO zones VALUES ('',99,'RJ','Rajasthan');
INSERT INTO zones VALUES ('',99,'PB','Punjab');
INSERT INTO zones VALUES ('',99,'HR','Haryana');
INSERT INTO zones VALUES ('',99,'CH','Chandigarh');
INSERT INTO zones VALUES ('',99,'JK','Jammu & Kashmir');
INSERT INTO zones VALUES ('',99,'HP','Himachal Pradesh');
INSERT INTO zones VALUES ('',99,'UA','Uttaranchal');
INSERT INTO zones VALUES ('',99,'LK','Lakshadweep');
INSERT INTO zones VALUES ('',99,'AN','Andaman & Nicobar');
INSERT INTO zones VALUES ('',99,'MG','Meghalaya');
INSERT INTO zones VALUES ('',99,'AS','Assam');
INSERT INTO zones VALUES ('',99,'DR','Dadra & Nagar Haveli');
INSERT INTO zones VALUES ('',99,'DN','Daman & Diu');
INSERT INTO zones VALUES ('',99,'SK','Sikkim');
INSERT INTO zones VALUES ('',99,'TR','Tripura');
INSERT INTO zones VALUES ('',99,'MZ','Mizoram');
INSERT INTO zones VALUES ('',99,'MN','Manipur');
INSERT INTO zones VALUES ('',99,'NL','Nagaland');
INSERT INTO zones VALUES ('',99,'AR','Arunachal Pradesh');

#Italy
INSERT INTO zones VALUES ('',105,'AG','Agrigento');
INSERT INTO zones VALUES ('',105,'AL','Alessandria');
INSERT INTO zones VALUES ('',105,'AN','Ancona');
INSERT INTO zones VALUES ('',105,'AO','Aosta');
INSERT INTO zones VALUES ('',105,'AR','Arezzo');
INSERT INTO zones VALUES ('',105,'AP','Ascoli Piceno');
INSERT INTO zones VALUES ('',105,'AT','Asti');
INSERT INTO zones VALUES ('',105,'AV','Avellino');
INSERT INTO zones VALUES ('',105,'BA','Bari');
INSERT INTO zones VALUES ('',105,'BT','Barletta-Andria-Trani');
INSERT INTO zones VALUES ('',105,'BL','Belluno');
INSERT INTO zones VALUES ('',105,'BN','Benevento');
INSERT INTO zones VALUES ('',105,'BG','Bergamo');
INSERT INTO zones VALUES ('',105,'BI','Biella');
INSERT INTO zones VALUES ('',105,'BO','Bologna');
INSERT INTO zones VALUES ('',105,'BZ','Bolzano');
INSERT INTO zones VALUES ('',105,'BS','Brescia');
INSERT INTO zones VALUES ('',105,'BR','Brindisi');
INSERT INTO zones VALUES ('',105,'CA','Cagliari');
INSERT INTO zones VALUES ('',105,'CL','Caltanissetta');
INSERT INTO zones VALUES ('',105,'CB','Campobasso');
INSERT INTO zones VALUES ('',105,'CI','Carbonia-Iglesias');
INSERT INTO zones VALUES ('',105,'CE','Caserta');
INSERT INTO zones VALUES ('',105,'CT','Catania');
INSERT INTO zones VALUES ('',105,'CZ','Catanzaro');
INSERT INTO zones VALUES ('',105,'CH','Chieti');
INSERT INTO zones VALUES ('',105,'CO','Como');
INSERT INTO zones VALUES ('',105,'CS','Cosenza');
INSERT INTO zones VALUES ('',105,'CR','Cremona');
INSERT INTO zones VALUES ('',105,'KR','Crotone');
INSERT INTO zones VALUES ('',105,'CN','Cuneo');
INSERT INTO zones VALUES ('',105,'EN','Enna');
INSERT INTO zones VALUES ('',105,'FM','Fermo');
INSERT INTO zones VALUES ('',105,'FE','Ferrara');
INSERT INTO zones VALUES ('',105,'FI','Firenze');
INSERT INTO zones VALUES ('',105,'FG','Foggia');
INSERT INTO zones VALUES ('',105,'FC','Forlì-Cesena');
INSERT INTO zones VALUES ('',105,'FR','Frosinone');
INSERT INTO zones VALUES ('',105,'GE','Genova');
INSERT INTO zones VALUES ('',105,'GO','Gorizia');
INSERT INTO zones VALUES ('',105,'GR','Grosseto');
INSERT INTO zones VALUES ('',105,'IM','Imperia');
INSERT INTO zones VALUES ('',105,'IS','Isernia');
INSERT INTO zones VALUES ('',105,'SP','La Spezia');
INSERT INTO zones VALUES ('',105,'AQ','Aquila');
INSERT INTO zones VALUES ('',105,'LT','Latina');
INSERT INTO zones VALUES ('',105,'LE','Lecce');
INSERT INTO zones VALUES ('',105,'LC','Lecco');
INSERT INTO zones VALUES ('',105,'LI','Livorno');
INSERT INTO zones VALUES ('',105,'LO','Lodi');
INSERT INTO zones VALUES ('',105,'LU','Lucca');
INSERT INTO zones VALUES ('',105,'MC','Macerata');
INSERT INTO zones VALUES ('',105,'MN','Mantova');
INSERT INTO zones VALUES ('',105,'MS','Massa-Carrara');
INSERT INTO zones VALUES ('',105,'MT','Matera');
INSERT INTO zones VALUES ('',105,'ME','Messina');
INSERT INTO zones VALUES ('',105,'MI','Milano');
INSERT INTO zones VALUES ('',105,'MO','Modena');
INSERT INTO zones VALUES ('',105,'MB','Monza e della Brianza');
INSERT INTO zones VALUES ('',105,'NA','Napoli');
INSERT INTO zones VALUES ('',105,'NO','Novara');
INSERT INTO zones VALUES ('',105,'NU','Nuoro');
INSERT INTO zones VALUES ('',105,'OT','Olbia-Tempio');
INSERT INTO zones VALUES ('',105,'OR','Oristano');
INSERT INTO zones VALUES ('',105,'PD','Padova');
INSERT INTO zones VALUES ('',105,'PA','Palermo');
INSERT INTO zones VALUES ('',105,'PR','Parma');
INSERT INTO zones VALUES ('',105,'PV','Pavia');
INSERT INTO zones VALUES ('',105,'PG','Perugia');
INSERT INTO zones VALUES ('',105,'PU','Pesaro e Urbino');
INSERT INTO zones VALUES ('',105,'PE','Pescara');
INSERT INTO zones VALUES ('',105,'PC','Piacenza');
INSERT INTO zones VALUES ('',105,'PI','Pisa');
INSERT INTO zones VALUES ('',105,'PT','Pistoia');
INSERT INTO zones VALUES ('',105,'PN','Pordenone');
INSERT INTO zones VALUES ('',105,'PZ','Potenza');
INSERT INTO zones VALUES ('',105,'PO','Prato');
INSERT INTO zones VALUES ('',105,'RG','Ragusa');
INSERT INTO zones VALUES ('',105,'RA','Ravenna');
INSERT INTO zones VALUES ('',105,'RC','Reggio di Calabria');
INSERT INTO zones VALUES ('',105,'RE','Reggio Emilia');
INSERT INTO zones VALUES ('',105,'RI','Rieti');
INSERT INTO zones VALUES ('',105,'RN','Rimini');
INSERT INTO zones VALUES ('',105,'RM','Roma');
INSERT INTO zones VALUES ('',105,'RO','Rovigo');
INSERT INTO zones VALUES ('',105,'SA','Salerno');
INSERT INTO zones VALUES ('',105,'VS','Medio Campidano');
INSERT INTO zones VALUES ('',105,'SS','Sassari');
INSERT INTO zones VALUES ('',105,'SV','Savona');
INSERT INTO zones VALUES ('',105,'SI','Siena');
INSERT INTO zones VALUES ('',105,'SR','Siracusa');
INSERT INTO zones VALUES ('',105,'SO','Sondrio');
INSERT INTO zones VALUES ('',105,'TA','Taranto');
INSERT INTO zones VALUES ('',105,'TE','Teramo');
INSERT INTO zones VALUES ('',105,'TR','Terni');
INSERT INTO zones VALUES ('',105,'TO','Torino');
INSERT INTO zones VALUES ('',105,'OG','Ogliastra');
INSERT INTO zones VALUES ('',105,'TP','Trapani');
INSERT INTO zones VALUES ('',105,'TN','Trento');
INSERT INTO zones VALUES ('',105,'TV','Treviso');
INSERT INTO zones VALUES ('',105,'TS','Trieste');
INSERT INTO zones VALUES ('',105,'UD','Udine');
INSERT INTO zones VALUES ('',105,'VA','Varese');
INSERT INTO zones VALUES ('',105,'VE','Venezia');
INSERT INTO zones VALUES ('',105,'VB','Verbania');
INSERT INTO zones VALUES ('',105,'VC','Vercelli');
INSERT INTO zones VALUES ('',105,'VR','Verona');
INSERT INTO zones VALUES ('',105,'VV','Vibo Valentia');
INSERT INTO zones VALUES ('',105,'VI','Vicenza');
INSERT INTO zones VALUES ('',105,'VT','Viterbo');

#Japan
INSERT INTO zones VALUES ('',107,'Niigata', 'Niigata');
INSERT INTO zones VALUES ('',107,'Toyama', 'Toyama');
INSERT INTO zones VALUES ('',107,'Ishikawa', 'Ishikawa');
INSERT INTO zones VALUES ('',107,'Fukui', 'Fukui');
INSERT INTO zones VALUES ('',107,'Yamanashi', 'Yamanashi');
INSERT INTO zones VALUES ('',107,'Nagano', 'Nagano');
INSERT INTO zones VALUES ('',107,'Gifu', 'Gifu');
INSERT INTO zones VALUES ('',107,'Shizuoka', 'Shizuoka');
INSERT INTO zones VALUES ('',107,'Aichi', 'Aichi');
INSERT INTO zones VALUES ('',107,'Mie', 'Mie');
INSERT INTO zones VALUES ('',107,'Shiga', 'Shiga');
INSERT INTO zones VALUES ('',107,'Kyoto', 'Kyoto');
INSERT INTO zones VALUES ('',107,'Osaka', 'Osaka');
INSERT INTO zones VALUES ('',107,'Hyogo', 'Hyogo');
INSERT INTO zones VALUES ('',107,'Nara', 'Nara');
INSERT INTO zones VALUES ('',107,'Wakayama', 'Wakayama');
INSERT INTO zones VALUES ('',107,'Tottori', 'Tottori');
INSERT INTO zones VALUES ('',107,'Shimane', 'Shimane');
INSERT INTO zones VALUES ('',107,'Okayama', 'Okayama');
INSERT INTO zones VALUES ('',107,'Hiroshima', 'Hiroshima');
INSERT INTO zones VALUES ('',107,'Yamaguchi', 'Yamaguchi');
INSERT INTO zones VALUES ('',107,'Tokushima', 'Tokushima');
INSERT INTO zones VALUES ('',107,'Kagawa', 'Kagawa');
INSERT INTO zones VALUES ('',107,'Ehime', 'Ehime');
INSERT INTO zones VALUES ('',107,'Kochi', 'Kochi');
INSERT INTO zones VALUES ('',107,'Fukuoka', 'Fukuoka');
INSERT INTO zones VALUES ('',107,'Saga', 'Saga');
INSERT INTO zones VALUES ('',107,'Nagasaki', 'Nagasaki');
INSERT INTO zones VALUES ('',107,'Kumamoto', 'Kumamoto');
INSERT INTO zones VALUES ('',107,'Oita', 'Oita');
INSERT INTO zones VALUES ('',107,'Miyazaki', 'Miyazaki');
INSERT INTO zones VALUES ('',107,'Kagoshima', 'Kagoshima');

#Malaysia
INSERT INTO zones VALUES ('',129,'JOH','Johor');
INSERT INTO zones VALUES ('',129,'KDH','Kedah');
INSERT INTO zones VALUES ('',129,'KEL','Kelantan');
INSERT INTO zones VALUES ('',129,'KL','Kuala Lumpur');
INSERT INTO zones VALUES ('',129,'MEL','Melaka');
INSERT INTO zones VALUES ('',129,'NS','Negeri Sembilan');
INSERT INTO zones VALUES ('',129,'PAH','Pahang');
INSERT INTO zones VALUES ('',129,'PRK','Perak');
INSERT INTO zones VALUES ('',129,'PER','Perlis');
INSERT INTO zones VALUES ('',129,'PP','Pulau Pinang');
INSERT INTO zones VALUES ('',129,'SAB','Sabah');
INSERT INTO zones VALUES ('',129,'SWK','Sarawak');
INSERT INTO zones VALUES ('',129,'SEL','Selangor');
INSERT INTO zones VALUES ('',129,'TER','Terengganu');
INSERT INTO zones VALUES ('',129,'LAB','W.P.Labuan');

#Mexico
INSERT INTO zones VALUES ('',138,'AGS','Aguascalientes');
INSERT INTO zones VALUES ('',138,'BC','Baja California');
INSERT INTO zones VALUES ('',138,'BCS','Baja California Sur');
INSERT INTO zones VALUES ('',138,'CAM','Campeche');
INSERT INTO zones VALUES ('',138,'COA','Coahuila');
INSERT INTO zones VALUES ('',138,'COL','Colima');
INSERT INTO zones VALUES ('',138,'CHI','Chiapas');
INSERT INTO zones VALUES ('',138,'CHIH','Chihuahua');
INSERT INTO zones VALUES ('',138,'DF','Distrito Federal');
INSERT INTO zones VALUES ('',138,'DGO','Durango');
INSERT INTO zones VALUES ('',138,'MEX','Estado de Mexico');
INSERT INTO zones VALUES ('',138,'GTO','Guanajuato');
INSERT INTO zones VALUES ('',138,'GRO','Guerrero');
INSERT INTO zones VALUES ('',138,'HGO','Hidalgo');
INSERT INTO zones VALUES ('',138,'JAL','Jalisco');
INSERT INTO zones VALUES ('',138,'MCH','Michoacan');
INSERT INTO zones VALUES ('',138,'MOR','Morelos');
INSERT INTO zones VALUES ('',138,'NAY','Nayarit');
INSERT INTO zones VALUES ('',138,'NL','Nuevo Leon');
INSERT INTO zones VALUES ('',138,'OAX','Oaxaca');
INSERT INTO zones VALUES ('',138,'PUE','Puebla');
INSERT INTO zones VALUES ('',138,'QRO','Queretaro');
INSERT INTO zones VALUES ('',138,'QR','Quintana Roo');
INSERT INTO zones VALUES ('',138,'SLP','San Luis Potosi');
INSERT INTO zones VALUES ('',138,'SIN','Sinaloa');
INSERT INTO zones VALUES ('',138,'SON','Sonora');
INSERT INTO zones VALUES ('',138,'TAB','Tabasco');
INSERT INTO zones VALUES ('',138,'TMPS','Tamaulipas');
INSERT INTO zones VALUES ('',138,'TLAX','Tlaxcala');
INSERT INTO zones VALUES ('',138,'VER','Veracruz');
INSERT INTO zones VALUES ('',138,'YUC','Yucatan');
INSERT INTO zones VALUES ('',138,'ZAC','Zacatecas');

#Norway
INSERT INTO zones VALUES ('',160,'OSL','Oslo');
INSERT INTO zones VALUES ('',160,'AKE','Akershus');
INSERT INTO zones VALUES ('',160,'AUA','Aust-Agder');
INSERT INTO zones VALUES ('',160,'BUS','Buskerud');
INSERT INTO zones VALUES ('',160,'FIN','Finnmark');
INSERT INTO zones VALUES ('',160,'HED','Hedmark');
INSERT INTO zones VALUES ('',160,'HOR','Hordaland');
INSERT INTO zones VALUES ('',160,'MOR','Møre og Romsdal');
INSERT INTO zones VALUES ('',160,'NOR','Nordland');
INSERT INTO zones VALUES ('',160,'NTR','Nord-Trøndelag');
INSERT INTO zones VALUES ('',160,'OPP','Oppland');
INSERT INTO zones VALUES ('',160,'ROG','Rogaland');
INSERT INTO zones VALUES ('',160,'SOF','Sogn og Fjordane');
INSERT INTO zones VALUES ('',160,'STR','Sør-Trøndelag');
INSERT INTO zones VALUES ('',160,'TEL','Telemark');
INSERT INTO zones VALUES ('',160,'TRO','Troms');
INSERT INTO zones VALUES ('',160,'VEA','Vest-Agder');
INSERT INTO zones VALUES ('',160,'OST','Østfold');
INSERT INTO zones VALUES ('',160,'SVA','Svalbard');

#Pakistan
INSERT INTO zones VALUES ('',162,'KHI','Karachi');
INSERT INTO zones VALUES ('',162,'LH','Lahore');
INSERT INTO zones VALUES ('',162,'ISB','Islamabad');
INSERT INTO zones VALUES ('',162,'QUE','Quetta');
INSERT INTO zones VALUES ('',162,'PSH','Peshawar');
INSERT INTO zones VALUES ('',162,'GUJ','Gujrat');
INSERT INTO zones VALUES ('',162,'SAH','Sahiwal');
INSERT INTO zones VALUES ('',162,'FSB','Faisalabad');
INSERT INTO zones VALUES ('',162,'RIP','Rawal Pindi');

#Romania
INSERT INTO zones VALUES ('',175,'AB','Alba');
INSERT INTO zones VALUES ('',175,'AR','Arad');
INSERT INTO zones VALUES ('',175,'AG','Arges');
INSERT INTO zones VALUES ('',175,'BC','Bacau');
INSERT INTO zones VALUES ('',175,'BH','Bihor');
INSERT INTO zones VALUES ('',175,'BN','Bistrita-Nasaud');
INSERT INTO zones VALUES ('',175,'BT','Botosani');
INSERT INTO zones VALUES ('',175,'BV','Brasov');
INSERT INTO zones VALUES ('',175,'BR','Braila');
INSERT INTO zones VALUES ('',175,'B','Bucuresti');
INSERT INTO zones VALUES ('',175,'BZ','Buzau');
INSERT INTO zones VALUES ('',175,'CS','Caras-Severin');
INSERT INTO zones VALUES ('',175,'CL','Calarasi');
INSERT INTO zones VALUES ('',175,'CJ','Cluj');
INSERT INTO zones VALUES ('',175,'CT','Constanta');
INSERT INTO zones VALUES ('',175,'CV','Covasna');
INSERT INTO zones VALUES ('',175,'DB','Dimbovita');
INSERT INTO zones VALUES ('',175,'DJ','Dolj');
INSERT INTO zones VALUES ('',175,'GL','Galati');
INSERT INTO zones VALUES ('',175,'GR','Giurgiu');
INSERT INTO zones VALUES ('',175,'GJ','Gorj');
INSERT INTO zones VALUES ('',175,'HR','Harghita');
INSERT INTO zones VALUES ('',175,'HD','Hunedoara');
INSERT INTO zones VALUES ('',175,'IL','Ialomita');
INSERT INTO zones VALUES ('',175,'IS','Iasi');
INSERT INTO zones VALUES ('',175,'IF','Ilfov');
INSERT INTO zones VALUES ('',175,'MM','Maramures');
INSERT INTO zones VALUES ('',175,'MH','Mehedint');
INSERT INTO zones VALUES ('',175,'MS','Mures');
INSERT INTO zones VALUES ('',175,'NT','Neamt');
INSERT INTO zones VALUES ('',175,'OT','Olt');
INSERT INTO zones VALUES ('',175,'PH','Prahova');
INSERT INTO zones VALUES ('',175,'SM','Satu-Mare');
INSERT INTO zones VALUES ('',175,'SJ','Salaj');
INSERT INTO zones VALUES ('',175,'SB','Sibiu');
INSERT INTO zones VALUES ('',175,'SV','Suceava');
INSERT INTO zones VALUES ('',175,'TR','Teleorman');
INSERT INTO zones VALUES ('',175,'TM','Timis');
INSERT INTO zones VALUES ('',175,'TL','Tulcea');
INSERT INTO zones VALUES ('',175,'VS','Vaslui');
INSERT INTO zones VALUES ('',175,'VL','Valcea');
INSERT INTO zones VALUES ('',175,'VN','Vrancea');

#South Africa
INSERT INTO zones VALUES ('',193,'WP','Western Cape');
INSERT INTO zones VALUES ('',193,'GP','Gauteng');
INSERT INTO zones VALUES ('',193,'KZN','Kwazulu-Natal');
INSERT INTO zones VALUES ('',193,'NC','Northern-Cape');
INSERT INTO zones VALUES ('',193,'EC','Eastern-Cape');
INSERT INTO zones VALUES ('',193,'MP','Mpumalanga');
INSERT INTO zones VALUES ('',193,'NW','North-West');
INSERT INTO zones VALUES ('',193,'FS','Free State');
INSERT INTO zones VALUES ('',193,'NP','Northern Province');

#Turkey
INSERT INTO zones VALUES ('',215,'AA', 'Adana');
INSERT INTO zones VALUES ('',215,'AD', 'Adiyaman');
INSERT INTO zones VALUES ('',215,'AF', 'Afyonkarahisar');
INSERT INTO zones VALUES ('',215,'AG', 'Agri');
INSERT INTO zones VALUES ('',215,'AK', 'Aksaray');
INSERT INTO zones VALUES ('',215,'AM', 'Amasya');
INSERT INTO zones VALUES ('',215,'AN', 'Ankara');
INSERT INTO zones VALUES ('',215,'AL', 'Antalya');
INSERT INTO zones VALUES ('',215,'AR', 'Ardahan');
INSERT INTO zones VALUES ('',215,'AV', 'Artvin');
INSERT INTO zones VALUES ('',215,'AY', 'Aydin');
INSERT INTO zones VALUES ('',215,'BK', 'Balikesir');
INSERT INTO zones VALUES ('',215,'BR', 'Bartin');
INSERT INTO zones VALUES ('',215,'BM', 'Batman');
INSERT INTO zones VALUES ('',215,'BB', 'Bayburt');
INSERT INTO zones VALUES ('',215,'BC', 'Bilecik');
INSERT INTO zones VALUES ('',215,'BG', 'Bingöl');
INSERT INTO zones VALUES ('',215,'BT', 'Bitlis');
INSERT INTO zones VALUES ('',215,'BL', 'Bolu' );
INSERT INTO zones VALUES ('',215,'BD', 'Burdur');
INSERT INTO zones VALUES ('',215,'BU', 'Bursa');
INSERT INTO zones VALUES ('',215,'CK', 'Çanakkale');
INSERT INTO zones VALUES ('',215,'CI', 'Çankiri');
INSERT INTO zones VALUES ('',215,'CM', 'Çorum');
INSERT INTO zones VALUES ('',215,'DN', 'Denizli');
INSERT INTO zones VALUES ('',215,'DY', 'Diyarbakir');
INSERT INTO zones VALUES ('',215,'DU', 'Düzce');
INSERT INTO zones VALUES ('',215,'ED', 'Edirne');
INSERT INTO zones VALUES ('',215,'EG', 'Elazig');
INSERT INTO zones VALUES ('',215,'EN', 'Erzincan');
INSERT INTO zones VALUES ('',215,'EM', 'Erzurum');
INSERT INTO zones VALUES ('',215,'ES', 'Eskisehir');
INSERT INTO zones VALUES ('',215,'GA', 'Gaziantep');
INSERT INTO zones VALUES ('',215,'GI', 'Giresun');
INSERT INTO zones VALUES ('',215,'GU', 'Gümüshane');
INSERT INTO zones VALUES ('',215,'HK', 'Hakkari');
INSERT INTO zones VALUES ('',215,'HT', 'Hatay');
INSERT INTO zones VALUES ('',215,'IG', 'Igdir');
INSERT INTO zones VALUES ('',215,'IP', 'Isparta');
INSERT INTO zones VALUES ('',215,'IB', 'Istanbul');
INSERT INTO zones VALUES ('',215,'IZ', 'Izmir');
INSERT INTO zones VALUES ('',215,'KM', 'Kahramanmaras');
INSERT INTO zones VALUES ('',215,'KB', 'Karabük');
INSERT INTO zones VALUES ('',215,'KR', 'Karaman');
INSERT INTO zones VALUES ('',215,'KA', 'Kars');
INSERT INTO zones VALUES ('',215,'KS', 'Kastamonu');
INSERT INTO zones VALUES ('',215,'KY', 'Kayseri');
INSERT INTO zones VALUES ('',215,'KI', 'Kilis');
INSERT INTO zones VALUES ('',215,'KK', 'Kirikkale');
INSERT INTO zones VALUES ('',215,'KL', 'Kirklareli');
INSERT INTO zones VALUES ('',215,'KH', 'Kirsehir');
INSERT INTO zones VALUES ('',215,'KC', 'Kocaeli');
INSERT INTO zones VALUES ('',215,'KO', 'Konya');
INSERT INTO zones VALUES ('',215,'KU', 'Kütahya');
INSERT INTO zones VALUES ('',215,'ML', 'Malatya');
INSERT INTO zones VALUES ('',215,'MN', 'Manisa');
INSERT INTO zones VALUES ('',215,'MR', 'Mardin');
INSERT INTO zones VALUES ('',215,'IC', 'Mersin');
INSERT INTO zones VALUES ('',215,'MG', 'Mugla');
INSERT INTO zones VALUES ('',215,'MS', 'Mus');
INSERT INTO zones VALUES ('',215,'NV', 'Nevsehir');
INSERT INTO zones VALUES ('',215,'NG', 'Nigde');
INSERT INTO zones VALUES ('',215,'OR', 'Ordu');
INSERT INTO zones VALUES ('',215,'OS', 'Osmaniye');
INSERT INTO zones VALUES ('',215,'RI', 'Rize');
INSERT INTO zones VALUES ('',215,'SK', 'Sakarya');
INSERT INTO zones VALUES ('',215,'SS', 'Samsun');
INSERT INTO zones VALUES ('',215,'SU', 'Sanliurfa');
INSERT INTO zones VALUES ('',215,'SI', 'Siirt');
INSERT INTO zones VALUES ('',215,'SP', 'Sinop');
INSERT INTO zones VALUES ('',215,'SR', 'Sirnak');
INSERT INTO zones VALUES ('',215,'SV', 'Sivas');
INSERT INTO zones VALUES ('',215,'TG', 'Tekirdag');
INSERT INTO zones VALUES ('',215,'TT', 'Tokat');
INSERT INTO zones VALUES ('',215,'TB', 'Trabzon');
INSERT INTO zones VALUES ('',215,'TC', 'Tunceli');
INSERT INTO zones VALUES ('',215,'US', 'Usak');
INSERT INTO zones VALUES ('',215,'VA', 'Van');
INSERT INTO zones VALUES ('',215,'YL', 'Yalova');
INSERT INTO zones VALUES ('',215,'YZ', 'Yozgat');
INSERT INTO zones VALUES ('',215,'ZO', 'Zonguldak');

#Venezuela
INSERT INTO zones VALUES ('',229,'AM','Amazonas');
INSERT INTO zones VALUES ('',229,'AN','Anzoátegui');
INSERT INTO zones VALUES ('',229,'AR','Aragua');
INSERT INTO zones VALUES ('',229,'AP','Apure');
INSERT INTO zones VALUES ('',229,'BA','Barinas');
INSERT INTO zones VALUES ('',229,'BO','Bolívar');
INSERT INTO zones VALUES ('',229,'CA','Carabobo');
INSERT INTO zones VALUES ('',229,'CO','Cojedes');
INSERT INTO zones VALUES ('',229,'DA','Delta Amacuro');
INSERT INTO zones VALUES ('',229,'DC','Distrito Capital');
INSERT INTO zones VALUES ('',229,'FA','Falcón');
INSERT INTO zones VALUES ('',229,'GA','Guárico');
INSERT INTO zones VALUES ('',229,'GU','Guayana');
INSERT INTO zones VALUES ('',229,'LA','Lara');
INSERT INTO zones VALUES ('',229,'ME','Mérida');
INSERT INTO zones VALUES ('',229,'MI','Miranda');
INSERT INTO zones VALUES ('',229,'MO','Monagas');
INSERT INTO zones VALUES ('',229,'NE','Nueva Esparta');
INSERT INTO zones VALUES ('',229,'PO','Portuguesa');
INSERT INTO zones VALUES ('',229,'SU','Sucre');
INSERT INTO zones VALUES ('',229,'TA','Táchira');
INSERT INTO zones VALUES ('',229,'TU','Trujillo');
INSERT INTO zones VALUES ('',229,'VA','Vargas');
INSERT INTO zones VALUES ('',229,'YA','Yaracuy');
INSERT INTO zones VALUES ('',229,'ZU','Zulia');

#UK
INSERT INTO zones VALUES ('',222,'BAS','Bath and North East Somerset');
INSERT INTO zones VALUES ('',222,'BDF','Bedfordshire');
INSERT INTO zones VALUES ('',222,'WBK','Berkshire');
INSERT INTO zones VALUES ('',222,'BBD','Blackburn with Darwen');
INSERT INTO zones VALUES ('',222,'BPL','Blackpool');
INSERT INTO zones VALUES ('',222,'BPL','Bournemouth');
INSERT INTO zones VALUES ('',222,'BNH','Brighton and Hove');
INSERT INTO zones VALUES ('',222,'BST','Bristol');
INSERT INTO zones VALUES ('',222,'BKM','Buckinghamshire');
INSERT INTO zones VALUES ('',222,'CAM','Cambridgeshire');
INSERT INTO zones VALUES ('',222,'CHS','Cheshire');
INSERT INTO zones VALUES ('',222,'CON','Cornwall');
INSERT INTO zones VALUES ('',222,'DUR','County Durham');
INSERT INTO zones VALUES ('',222,'CMA','Cumbria');
INSERT INTO zones VALUES ('',222,'DAL','Darlington');
INSERT INTO zones VALUES ('',222,'DER','Derby');
INSERT INTO zones VALUES ('',222,'DBY','Derbyshire');
INSERT INTO zones VALUES ('',222,'DEV','Devon');
INSERT INTO zones VALUES ('',222,'DOR','Dorset');
INSERT INTO zones VALUES ('',222,'ERY','East Riding of Yorkshire');
INSERT INTO zones VALUES ('',222,'ESX','East Sussex');
INSERT INTO zones VALUES ('',222,'ESS','Essex');
INSERT INTO zones VALUES ('',222,'GLS','Gloucestershire');
INSERT INTO zones VALUES ('',222,'LND','Greater London');
INSERT INTO zones VALUES ('',222,'MAN','Greater Manchester');
INSERT INTO zones VALUES ('',222,'HAL','Halton');
INSERT INTO zones VALUES ('',222,'HAM','Hampshire');
INSERT INTO zones VALUES ('',222,'HPL','Hartlepool');
INSERT INTO zones VALUES ('',222,'HEF','Herefordshire');
INSERT INTO zones VALUES ('',222,'HRT','Hertfordshire');
INSERT INTO zones VALUES ('',222,'KHL','Hull');
INSERT INTO zones VALUES ('',222,'IOW','Isle of Wight');
INSERT INTO zones VALUES ('',222,'KEN','Kent');
INSERT INTO zones VALUES ('',222,'LAN','Lancashire');
INSERT INTO zones VALUES ('',222,'LCE','Leicester');
INSERT INTO zones VALUES ('',222,'LEC','Leicestershire');
INSERT INTO zones VALUES ('',222,'LIN','Lincolnshire');
INSERT INTO zones VALUES ('',222,'LUT','Luton');
INSERT INTO zones VALUES ('',222,'MDW','Medway');
INSERT INTO zones VALUES ('',222,'MER','Merseyside');
INSERT INTO zones VALUES ('',222,'MDB','Middlesbrough');
INSERT INTO zones VALUES ('',222,'MDB','Milton Keynes');
INSERT INTO zones VALUES ('',222,'NFK','Norfolk');
INSERT INTO zones VALUES ('',222,'NTH','Northamptonshire');
INSERT INTO zones VALUES ('',222,'NEL','North East Lincolnshire');
INSERT INTO zones VALUES ('',222,'NLN','North Lincolnshire');
INSERT INTO zones VALUES ('',222,'NSM','North Somerset');
INSERT INTO zones VALUES ('',222,'NBL','Northumberland');
INSERT INTO zones VALUES ('',222,'NYK','North Yorkshire');
INSERT INTO zones VALUES ('',222,'NGM','Nottingham');
INSERT INTO zones VALUES ('',222,'NTT','Nottinghamshire');
INSERT INTO zones VALUES ('',222,'OXF','Oxfordshire');
INSERT INTO zones VALUES ('',222,'PTE','Peterborough');
INSERT INTO zones VALUES ('',222,'PLY','Plymouth');
INSERT INTO zones VALUES ('',222,'POL','Poole');
INSERT INTO zones VALUES ('',222,'POR','Portsmouth');
INSERT INTO zones VALUES ('',222,'RCC','Redcar and Cleveland');
INSERT INTO zones VALUES ('',222,'RUT','Rutland');
INSERT INTO zones VALUES ('',222,'SHR','Shropshire');
INSERT INTO zones VALUES ('',222,'SOM','Somerset');
INSERT INTO zones VALUES ('',222,'STH','Southampton');
INSERT INTO zones VALUES ('',222,'SOS','Southend-on-Sea');
INSERT INTO zones VALUES ('',222,'SGC','South Gloucestershire');
INSERT INTO zones VALUES ('',222,'SYK','South Yorkshire');
INSERT INTO zones VALUES ('',222,'STS','Staffordshire');
INSERT INTO zones VALUES ('',222,'STT','Stockton-on-Tees');
INSERT INTO zones VALUES ('',222,'STE','Stoke-on-Trent');
INSERT INTO zones VALUES ('',222,'SFK','Suffolk');
INSERT INTO zones VALUES ('',222,'SRY','Surrey');
INSERT INTO zones VALUES ('',222,'SWD','Swindon');
INSERT INTO zones VALUES ('',222,'TFW','Telford and Wrekin');
INSERT INTO zones VALUES ('',222,'THR','Thurrock');
INSERT INTO zones VALUES ('',222,'TOB','Torbay');
INSERT INTO zones VALUES ('',222,'TYW','Tyne and Wear');
INSERT INTO zones VALUES ('',222,'WRT','Warrington');
INSERT INTO zones VALUES ('',222,'WAR','Warwickshire');
INSERT INTO zones VALUES ('',222,'WMI','West Midlands');
INSERT INTO zones VALUES ('',222,'WSX','West Sussex');
INSERT INTO zones VALUES ('',222,'WYK','West Yorkshire');
INSERT INTO zones VALUES ('',222,'WIL','Wiltshire');
INSERT INTO zones VALUES ('',222,'WOR','Worcestershire');
INSERT INTO zones VALUES ('',222,'YOR','York');