INSERT INTO cseo_lang_button (id, button, buttontext, language_id) VALUES('', 'IMAGE_BUTTON_ADD_ADDRESS', 'new address', 1);
INSERT INTO cseo_lang_button (id, button, buttontext, language_id) VALUES('', 'IMAGE_BUTTON_BACK', 'back', 1);
INSERT INTO cseo_lang_button (id, button, buttontext, language_id) VALUES('', 'IMAGE_BUTTON_CHANGE_ADDRESS', 'change address', 1);
INSERT INTO cseo_lang_button (id, button, buttontext, language_id) VALUES('', 'IMAGE_BUTTON_CHECKOUT', 'checkout', 1);
INSERT INTO cseo_lang_button (id, button, buttontext, language_id) VALUES('', 'IMAGE_BUTTON_CONFIRM_ORDER', 'order', 1);
INSERT INTO cseo_lang_button (id, button, buttontext, language_id) VALUES('', 'IMAGE_BUTTON_CONTINUE', 'next', 1);
INSERT INTO cseo_lang_button (id, button, buttontext, language_id) VALUES('', 'IMAGE_BUTTON_DELETE', 'delete', 1);
INSERT INTO cseo_lang_button (id, button, buttontext, language_id) VALUES('', 'IMAGE_BUTTON_LOGIN', 'login', 1);
INSERT INTO cseo_lang_button (id, button, buttontext, language_id) VALUES('', 'IMAGE_BUTTON_IN_CART', 'into the cart', 1);
INSERT INTO cseo_lang_button (id, button, buttontext, language_id) VALUES('', 'IMAGE_BUTTON_SEARCH', 'go', 1);
INSERT INTO cseo_lang_button (id, button, buttontext, language_id) VALUES('', 'IMAGE_BUTTON_PRINT', 'print', 1);
INSERT INTO cseo_lang_button (id, button, buttontext, language_id) VALUES('', 'IMAGE_BUTTON_ADD_A_QUICKIE', 'add', 1);
INSERT INTO cseo_lang_button (id, button, buttontext, language_id) VALUES('', 'IMAGE_BUTTON_UPDATE', 'update', 1);
INSERT INTO cseo_lang_button (id, button, buttontext, language_id) VALUES('', 'IMAGE_BUTTON_UPDATE_CART', 'update shopping cart', 1);
INSERT INTO cseo_lang_button (id, button, buttontext, language_id) VALUES('', 'IMAGE_BUTTON_WRITE_REVIEW', 'write Evaluation', 1);
INSERT INTO cseo_lang_button (id, button, buttontext, language_id) VALUES('', 'IMAGE_BUTTON_ADMIN', 'admin', 1);
INSERT INTO cseo_lang_button (id, button, buttontext, language_id) VALUES('', 'IMAGE_BUTTON_MOBILE_ADMIN', 'mobile-admin', 1);
INSERT INTO cseo_lang_button (id, button, buttontext, language_id) VALUES('', 'IMAGE_BUTTON_PRODUCT_EDIT', 'edit product', 1);
INSERT INTO cseo_lang_button (id, button, buttontext, language_id) VALUES('', 'IMAGE_BUTTON_PRINT_PDF', 'create PDF and show me', 1);
INSERT INTO cseo_lang_button (id, button, buttontext, language_id) VALUES('', 'IMAGE_BUTTON_PRINT_CONTENT', 'print text', 1);
INSERT INTO cseo_lang_button (id, button, buttontext, language_id) VALUES('', 'IMAGE_BUTTON_SEND', 'send', 1);
INSERT INTO cseo_lang_button (id, button, buttontext, language_id) VALUES('', 'IMAGE_BUTTON_SAVE', 'save', 1);
INSERT INTO cseo_lang_button (id, button, buttontext, language_id) VALUES('', 'IMAGE_BUTTON_EDIT', 'edit', 1);
INSERT INTO cseo_lang_button (id, button, buttontext, language_id) VALUES('', 'IMAGE_BUTTON_DETAILS', 'details', 1);
INSERT INTO cseo_lang_button (id, button, buttontext, language_id) VALUES('', 'IMAGE_BUTTON_ALL_WISH', 'buy all', 1);
INSERT INTO cseo_lang_button (id, button, buttontext, language_id) VALUES('', 'IMAGE_BUTTON_MORE_NEWS', 'more news', 1);
INSERT INTO cseo_lang_button (id, button, buttontext, language_id) VALUES('', 'IMAGE_BUTTON_TO_CART', 'to cart', 1);
INSERT INTO cseo_lang_button (id, button, buttontext, language_id) VALUES('', 'IMAGE_BUTTON_BACK_SHOP', 'back to shop', 1);
INSERT INTO cseo_lang_button (id, button, buttontext, language_id) VALUES('', 'IMAGE_BUTTON_VOTE', 'vote this shop', 1);
INSERT INTO cseo_lang_button (id, button, buttontext, language_id) VALUES('', 'TEXT_NOW', 'order', 1);
INSERT INTO cseo_lang_button (id, button, buttontext, language_id) VALUES('', 'TEXT_BUTTON_BUY_NOW', 'order', 1);
INSERT INTO cseo_lang_button (id, button, buttontext, language_id) VALUES('', 'TEXT_NOW_TO_WISHLIST', 'to the wish list', 1);
INSERT INTO cseo_lang_button (id, button, buttontext, language_id) VALUES('', 'TEXT_TO_WISHLIST', 'to wish list', 1);
INSERT INTO cseo_lang_button (id, button, buttontext, language_id) VALUES('', 'WISHLIST', 'wish', 1);
INSERT INTO cseo_lang_button (id, button, buttontext, language_id) VALUES('', 'TEXT_UVP', 'NBI', 1);
INSERT INTO cseo_lang_button (id, button, buttontext, language_id) VALUES('', 'PRODUCT_ONLY_REQUEST', 'only request', 1);

INSERT INTO cseo_lang_button (id, button, buttontext, language_id) VALUES('', 'IMAGE_BUTTON_ADD_ADDRESS', 'Neue Adresse', 2);
INSERT INTO cseo_lang_button (id, button, buttontext, language_id) VALUES('', 'IMAGE_BUTTON_BACK', 'zurück', 2);
INSERT INTO cseo_lang_button (id, button, buttontext, language_id) VALUES('', 'IMAGE_BUTTON_CHANGE_ADDRESS', 'Adresse ändern', 2);
INSERT INTO cseo_lang_button (id, button, buttontext, language_id) VALUES('', 'IMAGE_BUTTON_CHECKOUT', 'zur Kasse', 2);
INSERT INTO cseo_lang_button (id, button, buttontext, language_id) VALUES('', 'IMAGE_BUTTON_CONFIRM_ORDER', 'Zahlungspflichtig bestellen', 2);
INSERT INTO cseo_lang_button (id, button, buttontext, language_id) VALUES('', 'IMAGE_BUTTON_CONTINUE', 'Weiter', 2);
INSERT INTO cseo_lang_button (id, button, buttontext, language_id) VALUES('', 'IMAGE_BUTTON_DELETE', 'Löschen', 2);
INSERT INTO cseo_lang_button (id, button, buttontext, language_id) VALUES('', 'IMAGE_BUTTON_LOGIN', 'Anmelden', 2);
INSERT INTO cseo_lang_button (id, button, buttontext, language_id) VALUES('', 'IMAGE_BUTTON_IN_CART', 'In den Warenkorb', 2);
INSERT INTO cseo_lang_button (id, button, buttontext, language_id) VALUES('', 'IMAGE_BUTTON_SEARCH', 'Los', 2);
INSERT INTO cseo_lang_button (id, button, buttontext, language_id) VALUES('', 'IMAGE_BUTTON_PRINT', 'Drucken', 2);
INSERT INTO cseo_lang_button (id, button, buttontext, language_id) VALUES('', 'IMAGE_BUTTON_ADD_A_QUICKIE', 'Bestellen', 2);
INSERT INTO cseo_lang_button (id, button, buttontext, language_id) VALUES('', 'IMAGE_BUTTON_UPDATE', 'Aktualisieren', 2);
INSERT INTO cseo_lang_button (id, button, buttontext, language_id) VALUES('', 'IMAGE_BUTTON_UPDATE_CART', 'Warenkorb aktualisieren', 2);
INSERT INTO cseo_lang_button (id, button, buttontext, language_id) VALUES('', 'IMAGE_BUTTON_WRITE_REVIEW', 'Bewertung schreiben', 2);
INSERT INTO cseo_lang_button (id, button, buttontext, language_id) VALUES('', 'IMAGE_BUTTON_ADMIN', 'Admin', 2);
INSERT INTO cseo_lang_button (id, button, buttontext, language_id) VALUES('', 'IMAGE_BUTTON_MOBILE_ADMIN', 'Mobile-Admin', 2);
INSERT INTO cseo_lang_button (id, button, buttontext, language_id) VALUES('', 'IMAGE_BUTTON_PRODUCT_EDIT', 'Produkt bearbeiten', 2);
INSERT INTO cseo_lang_button (id, button, buttontext, language_id) VALUES('', 'IMAGE_BUTTON_PRINT_PDF', 'PDF erzeugen und anzeigen', 2);
INSERT INTO cseo_lang_button (id, button, buttontext, language_id) VALUES('', 'IMAGE_BUTTON_PRINT_CONTENT', 'Text drucken', 2);
INSERT INTO cseo_lang_button (id, button, buttontext, language_id) VALUES('', 'IMAGE_BUTTON_SEND', 'Absenden', 2);
INSERT INTO cseo_lang_button (id, button, buttontext, language_id) VALUES('', 'IMAGE_BUTTON_SAVE', 'Speichern', 2);
INSERT INTO cseo_lang_button (id, button, buttontext, language_id) VALUES('', 'IMAGE_BUTTON_EDIT', 'bearbeiten', 2);
INSERT INTO cseo_lang_button (id, button, buttontext, language_id) VALUES('', 'IMAGE_BUTTON_DETAILS', 'Details', 2);
INSERT INTO cseo_lang_button (id, button, buttontext, language_id) VALUES('', 'IMAGE_BUTTON_ALL_WISH', 'kompletten Merkzettel bestellen', 2);
INSERT INTO cseo_lang_button (id, button, buttontext, language_id) VALUES('', 'IMAGE_BUTTON_MORE_NEWS', 'mehr anzeigen', 2);
INSERT INTO cseo_lang_button (id, button, buttontext, language_id) VALUES('', 'IMAGE_BUTTON_TO_CART', 'zum Warenkorb', 2);
INSERT INTO cseo_lang_button (id, button, buttontext, language_id) VALUES('', 'IMAGE_BUTTON_BACK_SHOP', 'zurück zum Shop', 2);
INSERT INTO cseo_lang_button (id, button, buttontext, language_id) VALUES('', 'IMAGE_BUTTON_VOTE', 'Shop bewerten', 2);
INSERT INTO cseo_lang_button (id, button, buttontext, language_id) VALUES('', 'TEXT_NOW', 'kaufen', 2);
INSERT INTO cseo_lang_button (id, button, buttontext, language_id) VALUES('', 'TEXT_BUTTON_BUY_NOW', 'kaufen', 2);
INSERT INTO cseo_lang_button (id, button, buttontext, language_id) VALUES('', 'TEXT_NOW_TO_WISHLIST', 'dem Merkzettel hinzufügen', 2);
INSERT INTO cseo_lang_button (id, button, buttontext, language_id) VALUES('', 'TEXT_TO_WISHLIST', 'zum Merkzettel', 2);
INSERT INTO cseo_lang_button (id, button, buttontext, language_id) VALUES('', 'WISHLIST', 'auf den Merkzettel', 2);
INSERT INTO cseo_lang_button (id, button, buttontext, language_id) VALUES('', 'TEXT_UVP', 'Unverbindliche Preisempfehlung:', 2);
INSERT INTO cseo_lang_button (id, button, buttontext, language_id) VALUES('', 'PRODUCT_ONLY_REQUEST', 'Auf Anfrage', 2);
